### ISSUE TITLE
Can not open CBT (Tar Comic Book)

### ISSUE THREAD

**Issue by GreenLunar** [mate-desktop/engrampa#109]
Could not create the archive

Archive type not supported.

**Comment by raveit65** [comment]
Do you have an archive for reproducing the issue?

**Comment by GreenLunar** [comment]
Just archive some images to a TAR file and rename it to CBT.

`wget http://mate-desktop.org/gallery/1.14/MATE-1.14_1.png http://mate-desktop.org/gallery/1.14/MATE-1.14_10.png http://mate-desktop.org/gallery/1.14/MATE-1.14_11.png http://mate-desktop.org/gallery/1.14/MATE-1.14_12.png http://mate-desktop.org/gallery/1.14/MATE-1.14_13.png http://mate-desktop.org/gallery/1.14/MATE-1.14_2.png http://mate-desktop.org/gallery/1.14/MATE-1.14_3.png http://mate-desktop.org/gallery/1.14/MATE-1.14_4.png http://mate-desktop.org/gallery/1.14/MATE-1.14_5.png http://mate-desktop.org/gallery/1.14/MATE-1.14_6.png http://mate-desktop.org/gallery/1.14/MATE-1.14_7.png http://mate-desktop.org/gallery/1.14/MATE-1.14_9.png http://mate-desktop.org/gallery/1.14/MATE-1.14_8.png`

Try also with CB7 (7Z), CBR (RAR), and CBZ (ZIP).

**Comment by raveit65** [comment]
But a .tar file is a uncompressed  tar archive and not a comic book archive, imo.
I don't think that simply renaming a archive change the archive type.
You only destroy the archive.

**Comment by GreenLunar** [comment]
I think you are wrong.  I do the same by renaming CB7 (7Z), CBR (RAR) and CBZ (ZIP), and Engrampa is able to read all of them.

**Comment by sc0w** [comment]
I think cbt is not supported

my reasons:

- Is not on src/fr-init.c , neither in file-roller

https://github.com/mate-desktop/engrampa/blob/master/src/fr-init.c

- this feature request in file-roller:

https://bugzilla.gnome.org/show_bug.cgi?id=694724

**Comment by sc0w** [comment]
seems now engrampa can open **.cbt** files

I don't know the reasons

I have tested with engrampa 1.16

@GreenLunar can you confirm?

**Comment by GreenLunar** [comment]
Not yet, I did not even upgrade to Slackware 14.2.
If I would encounter this issue again, I will reopen this issue.

P.S.
I really need a computer donation in order to keep a continuous flux of bug reports.
It is nice to see a Zenwalk user here ;)
