### ISSUE TITLE
Engrampa 1.12.0 on F23 shows nonexisting folder in all zip files (if p7zip is installed)

### ISSUE THREAD

**Issue by smikkelsendk** [mate-desktop/engrampa#112]
Engrampa 1.12.0 on F23 shows nonexisting folder in all zip files.

When opening a ZIP file it will show a nonexisting folder that points to the location where the file is opened, ie if zip file is opened in /tmp/test it will show that folder inside zip. If you move the zip filer the shown folder will change. 

![step1](https://cloud.githubusercontent.com/assets/3275361/11469655/2e0ded3c-9758-11e5-807a-37a121c0757e.png)
![step2](https://cloud.githubusercontent.com/assets/3275361/11469653/2e0b74c6-9758-11e5-89f5-643fb3bae8ad.png)
![info](https://cloud.githubusercontent.com/assets/3275361/11469652/2e0b6c42-9758-11e5-9821-c8e28feebc40.png)
![info2](https://cloud.githubusercontent.com/assets/3275361/11469654/2e0c1278-9758-11e5-9b11-f319211a663a.png)

**Comment by monsta** [comment]
Not reproducible in LMDE 2 "Betsy":

![engrampa-test](https://cloud.githubusercontent.com/assets/5138986/11471574/bee149e8-9777-11e5-8436-3511a994fa2c.png)

**Comment by raveit65** [comment]
reproducible if p7zip is installed in fedora 22/23.
Looks like an issue with p7zip itself or our implementation.
@monsta 
i'm pretty shure p7zip is missing :smile:

**Comment by smikkelsendk** [comment]
removing p7zip package on F23 fixes the problem for me

**Comment by monsta** [comment]
Hmm, p7zip is installed...

**Comment by raveit65** [comment]
@smikkelsendk 
with f22 i could downgrade p7zip to 9.20 which doesn't have this issue.
 f23 repos have the version too.

**Comment by raveit65** [comment]
@smikkelsendk 
Using 7zip 15.09-2 via command line has the same prob.
'7za a testfile.zip testfile.txt'
But all is fine with 9.20.
So the issue is in 7zip itself, i suggest to open a rhbz report for it against p7zip.

**Comment by smikkelsendk** [comment]
@raveit65 You might be right, but I fail to see how your 7za example demonstrates the problem.

If I run the list operation with 7za on the zip file I do not get any extra entries:

Scanning the drive for archives:
1 file, 158 bytes (1 KiB)

Listing archive: testfile.zip

--
Path = testfile.zip
Type = zip
Physical Size = 158

   Date      Time    Attr         Size   Compressed  Name
------------------- ----- ------------ ------------  ------------------------
2015-11-30 11:42:57 .....            0            0  testfile.txt
------------------- ----- ------------ ------------  ------------------------
2015-11-30 11:42:57                  0            0  1 files

**Comment by raveit65** [comment]
Well, '7zs l' does not list the folder.
But i see the folder also in file-roller.
So, something is changed in 7zip and only the maintaner or 7zip devs can say what is changed from 9.20 --> 15.09

**Comment by monsta** [comment]
Should be actually fixed by https://github.com/mate-desktop/engrampa/commit/4f65bde8fc4d4efe747d4e7fbeba1211469ed79a (see https://github.com/mate-desktop/engrampa/issues/114 and https://bugzilla.gnome.org/757793).

**Comment by raveit65** [comment]
confirmed, fixed with that commit
@smikkelsendk 
new engrampa build comming soon for fedora.

**Comment by raveit65** [comment]
@smikkelsendk 
https://bodhi.fedoraproject.org/updates/FEDORA-2015-ea91b4d6f3
