### ISSUE TITLE
Plural form

### ISSUE THREAD

**Issue by prescott66** [mate-desktop/engrampa#113]
Please create plural form for this string:

#: ../src/fr-window.c:2697
#, c-format
msgid "%'d files remaining"

DEV wiki: https://wiki.gnome.org/TranslationProject/DevGuidelines/Plurals

**Comment by monsta** [comment]
I thought it's already fixed in https://github.com/mate-desktop/engrampa/commit/2c856871591b413872b11f48bd725d71b8ebbc2a?

**Comment by monsta** [comment]
Oops, looks like the updated ```.pot``` file hasn't been pushed to Transifex. I've pushed it now.

**Comment by monsta** [comment]
I see translations are being updated on Transifex, should be ok now.
