### ISSUE TITLE
home folder in every archive

### ISSUE THREAD

**Issue by alexdrk** [mate-desktop/engrampa#115]
Hello, I'm using Engrampa (version: 1.12.0) and it seems there is a bug. Every archive I try to open contains a home folder and it contains a path to the zip file itself . I have attached two images. If there is any other information I can provide please, let me know!
![screenshot_2015-12-25_20-03-51](https://cloud.githubusercontent.com/assets/885135/12004048/c349033e-ab42-11e5-8d72-22c4a56ce2c1.png)
![screenshot_2015-12-25_20-03-22](https://cloud.githubusercontent.com/assets/885135/12004049/c34a834e-ab42-11e5-9006-f9130e817b76.png)

**Comment by raveit65** [comment]
Try uninstall p7zip (engrampa use unzip than) and try again please.
See
https://github.com/mate-desktop/engrampa/issues/112
https://github.com/mate-desktop/engrampa/issues/114

**Comment by alexdrk** [comment]
that actualy worked thanks!
