### ISSUE TITLE
Path to the ZIP file shown as being inside the ZIP file

### ISSUE THREAD

**Issue by assen-totin** [mate-desktop/engrampa#116]
This has only been tested with ZIP container files. 

When a ZIP file is opened in Engrampa, the path to the ZIP file is shown as being inside the ZIP file. As an example, if a ZIP file has a single directory named 'test' inside it and is placed on /home/user/Desktop, then opening the ZIP file in Engrampa shows to directories - the existing 'test' directory and a none-existing 'home' directory. Getting into the 'home' directory shows 'user' directory inside it, then 'Desktop' directory inside that and so on.

Screenshots from a test ZIP file with its actual contents and what Engrampa shows: 
https://drive.google.com/folderview?id=0B6LrbKUd63VQV3dRWUViRFgyVzA&usp=sharing

This happens every time a ZIP container is opened on Fedora 23 running engrampa-1.12.0-1.fc23.i686. Fedora 22 did not have this issue, so it is probably related to MATE 1.12 only.

**Comment by raveit65** [comment]
Hi, Assen,
see https://github.com/mate-desktop/engrampa/commit/4f65bde8fc4d4efe747d4e7fbeba1211469ed79a
Already fixed in  engrampa-1.12.0-2.fc23
 https://bodhi.fedoraproject.org/updates/FEDORA-2015-ea91b4d6f3
