### ISSUE TITLE
Engrampa doesn't respect overwrite settings

### ISSUE THREAD

**Issue by cranes-bill** [mate-desktop/engrampa#118]
In schema `org.mate.engrampa.dialogs.extract`, the `overwrite` is set to `true`, but Engrampa always showing a confirmation dialog when i attempting to extract over existing files.
Tested with both GTK+2 & GTK+3

**Comment by monsta** [comment]
How do you extract files? Via menu item, or via drag-n-drop to Caja window, or any other way?

**Comment by cranes-bill** [comment]
@monsta 
Drag-n-drop to Desktop in most cases and sometimes to other window, but it's the same.

**Comment by monsta** [comment]
Then you see a dialog shown by Caja.
The schema key you mentioned is for Engrampa's extract dialog (open an archive and press ```Ctrl-E```).

![extract](https://cloud.githubusercontent.com/assets/5138986/12750330/9204b6b2-c9c7-11e5-8774-5ce1a0446626.png)

**Comment by cranes-bill** [comment]
...which [also does not works](https://github.com/mate-desktop/engrampa/issues/122) :smile:

**Comment by monsta** [comment]
That checkbox works for me.

**Comment by cranes-bill** [comment]
Yep, if it checked, but if unchecked still overwrites, so that i referred to #122

**Comment by monsta** [comment]
Just tested - it doesn't overwrite when it's unchecked. I'm using the latest version from git master though.

**Comment by cranes-bill** [comment]
I can't test just right now, so i will report later (perhaps tomorrow) about that.

**Comment by cranes-bill** [comment]
OK, tested and it works to me as well.
But i'm only using _DRAG AND DROP_ and i would like to disable confirmation dialog, so can i do that as follow?:
```diff
--- src/fr-window.c	2016-02-03 09:28:23.898741190 +0200
+++ src/fr-window.c.new	2016-02-03 09:37:03.568224091 +0200
@@ -4243,7 +4243,7 @@
 					   window->priv->drag_destination_folder,
 					   window->priv->drag_base_dir,
 					   FALSE,
-					   FR_OVERWRITE_ASK,
+					   FR_OVERWRITE_YES,
 					   FALSE,
 					   FALSE);
 		path_list_free (window->priv->drag_file_list);
```
It works to me, but i would like to know that it will not cause a problem.
Thank you in advance!

**Comment by monsta** [comment]
Well of course it might cause problems for other users - I'm sure they won't like their files being silently overwritten. :smile:
Possible solution is to introduce a new GSettings key for that. The default value should be ```true``` in order to not make surprises for most users. You'll be able to change it to ```false``` if you wish so.
