### ISSUE TITLE
engrampa overwrites without confirmation

### ISSUE THREAD

**Issue by sc0w** [mate-desktop/engrampa#122]
Engrampa overwrites without confirmation in this cases:

1- on the engrampa menu, "archive" -> "extract..."

2- on caja, "right button" -> "extract to..."

**Comment by monsta** [comment]
Interesting... https://github.com/mate-desktop/engrampa/issues/118 is kind of opposite to this one... :smile:

**Comment by sc0w** [comment]
I think the #118 is with drag and drop from engrampa to caja

I suggest always ask whether to overwrite, and apply this file-roller commit:

https://git.gnome.org/browse/file-roller/commit/?id=fe71357aa128d029b6ca4a9493b8a408c8aaf017

**Comment by raveit65** [comment]
hmm, why not thinking about the action before clicking on extract button?
.....i don't like conformition dialogs very much. If it is possible i would disable all ;)

**Comment by monsta** [comment]
> I think the #118 is with drag and drop from engrampa to caja

You were right :smile: but see the screenshot - there's a checkbox for setting overwrite on/off.

Also, when I extract via Caja's right click menu, it doesn't overwrite, it creates a new file with a number added to it.

**Comment by sc0w** [comment]
it creates a new file with a number only on "extract here"

The "Overwrite existing files" checkbox dont works for me.

**Comment by sc0w** [comment]
I tested more details:

.zip (7z) .tar and .rar (unar) overwrites without confirmation 

only .rar with non-free rar dont overwrites without confirmation, but shows an error message ("No files to extract") instead the confirmation dialog

@monsta what formats you tested?

**Comment by monsta** [comment]
I've tested .zip, .tar.gz, .tar.xz. There won't be any additional confirmation dialog. If checkbox is checked, the files are overwritten, if not, they aren't. That's all.

**Comment by sc0w** [comment]
aha, ok, sorry

but there is a bug about non-free rar, shows the error message "No files to extract"
