### ISSUE TITLE
engrampa can not extract files with one char in its name (a, b, c, 1, 2, 3 ... )

### ISSUE THREAD

**Issue by sc0w** [mate-desktop/engrampa#125]
I tested with drag and drop:

1) If the file is not inside a folder, and exists on the destination dir, engrampa always overwrites without confirmation

2) If the file is inside a folder, engrampa can not extract it

This happens with files with one only char

**Comment by sc0w** [comment]
If I run engrampa with mate-terminal: (drag and drop)

(engrampa:9689): GLib-CRITICAL **: g_uri_escape_string: assertion 'unescaped != NULL' failed

**Comment by sc0w** [comment]
you can test this file

[bugengrampaonechar.zip](https://github.com/mate-desktop/engrampa/files/256049/bugengrampaonechar.zip)

**Comment by raveit65** [comment]
Confirmed, extracting from aa folder does not work.

**Comment by raveit65** [comment]
fix works great here.

**Comment by raveit65** [comment]
merged
https://github.com/mate-desktop/engrampa/commit/1af3e43014341b5112e90dd44b7c5504a62bf0bc
