### ISSUE TITLE
engrampa 1.12.0 cannot open Alienbob's slackware-live ISOs

### ISSUE THREAD

**Issue by burdi01** [mate-desktop/engrampa#128]
When opening one of Alienbob's slackware-live ISOs engrampa 1.12.0 complains about an unexpected end of archive. 
This can be tested with e.g. the mate ISO from http://slackware.uk/people/alien-slacklive/0.7.0/ .
Actually engrampa 1.8.1 and 1.10.2, file-roller 3.10.0 and ark 2.19 all happily open the ISOs. See the discussion on http://alien.slackbook.org/blog/new-iso-images-for-slackware-live-edition-beta-7/ .
Regards, Dick (D.L.C. Burggraaff aka burdi01).

**Comment by cranes-bill** [comment]
But trying to open the iso directly with 7zip, it gives the same error, so i think that's not a quite Engrampa issue, but most likely 7zip one.

**Comment by burdi01** [comment]
> ... that's not a quite Engrampa issue, but most likely 7zip one.

Yes and no. 7z 15.09 beta and 15.14.1 both display the "Unexpected end of archive" error message but they immediately follow on with a normal contents list.

![screenshot](https://cloud.githubusercontent.com/assets/9949014/14064729/8f805fd8-f40e-11e5-9cab-f8dee376d677.png)

 The older 7z 9.04 beta and 9.20 versions display the contents list without the error message.

The ISOs in question are oversized ones created with mkisofs and isohybrid:

> isohybrid: Warning: more than 1024 cylinders: 1711
> isohybrid: Not all BIOSes will be able to boot this device

7z 15.14.1 for the same ISOs created with xorriso displays a "There are data after the end of archive" warning message immediately followed on by the contents list and engrampa 1.12.0 does not complain.

**Comment by sc0w** [comment]
engrampa 1.12 with p7zip 9.20 works

I think file-roller works because it uses libarchive

I open the bug on p7zip:

https://sourceforge.net/p/p7zip/bugs/180/

**Comment by cranes-bill** [comment]
**Just a note**: Engrampa works as well, if `7z` is not installed.

**Comment by babam86** [comment]
P7Zip (Linux) and 7-Zip (Windows) is able to open this ISO file.

Engrampa is unable to open this ISO file.

**Comment by cranes-bill** [comment]
> Engrampa is unable to open this ISO file.

As i already told, only if `7z` binary is in `$PATH`...
![capture du 2016-05-26 10-10-07](https://cloud.githubusercontent.com/assets/5161278/15597786/5bd6f446-23dc-11e6-8279-d9aa47e4540d.png)

**Comment by burdi01** [comment]
Now testing with the ISOs from http://slackware.uk/people/alien-slacklive/1.0.0/ as the 0.7.0 ones are no longer available.

With 7z in the path engrampa 1.12.0 as well as 1.14.1 show the "unexpected end of archive" problem. I just noticed that the Physical Size as shown in the error message is 8796092989440 whatever the actual size of the ISO is. This behavior seems to be restricted to slacklive ISOs -- the ISOs of e.g. Fedora, Mint, Porteus, PartedMagic and Ubuntu are OK.

Without 7z in the path they the engrampas show an empty list for location "/". I see this behavior for the slacklive ISOs and the Porteus ones. The ISOs of Fedora, Mint, PartedMagic and Ubuntu are OK.

**Comment by babam86** [comment]
@cranes-bill

Please use P7zip >15.09 and then Engrampa unable to open this ISO file.

**Comment by cranes-bill** [comment]
@babam86 The version that i,m using is **15.14**.
Probably because of my bad English, you did not understand me properly, but the problem was pretty well described from @burdi01 in the comment before yours.

**Comment by sc0w** [comment]
https://sourceforge.net/p/p7zip/bugs/180/

> If you know why SLACKWARELIVE item contains negative "Location of Extent" value, please notifiy me.
Do you know what software was used to create that archive?

**Comment by babam86** [comment]
@sc0w

ISO file created with mkisofs.

**Comment by sc0w** [comment]
file-roller without libarchive has same problem

**Comment by sc0w** [comment]
@babam86 do you know all the args used to create the isos ? (the complete command line)

**Comment by babam86** [comment]
@sc0w

mkisofs -hide-rr-moved -l -v -d -iso-level 3 -r -J -V "example" -b boot/syslinux/isolinux.bin -c boot/syslinux/isolinux.boot -no-emul-boot -boot-load-size 4 -boot-info-table -eltorito-alt-boot -eltorito-platform 0xEF -eltorito-boot EFI/boot/efiboot.img -no-emul-boot -o "example.iso" example

**Comment by burdi01** [comment]
In http://forum.porteus.org/viewtopic.php?f=117&t=5928&start=90 "scdbackup" wrote:
" as developer of xorriso i have to nitpick that it is not the size of the ISO but the existence
" of empty files which makes mkisofs output indigestible for 7z.
" mkisofs uses block address 4294967280 (aka 0xfffffff0 aka -16) for files which are no
" directories and contain no data bytes.
" 7z checks sanity of block addresses versus ISO size.

In https://sourceforge.net/p/p7zip/bugs/180/ this was reported by "ZenWalker".
The response was "Probably I'll try to fix that thing".
:D
