### ISSUE TITLE
engrampa cannot extract .iso files 

### ISSUE THREAD

**Issue by nikzarif** [mate-desktop/engrampa#131]
I am using Asus A455LJ running Ubuntu Mate 15.10 (Wily Werewolf) 64-bit , Kernel Linux 4.2.0-35-generic x86_64 , Mate 1.10.2
Installed Engrampa 1.10.2
I have a few .aff files that i need to analyze. Those .aff files are Microsoft Windows OS that are forensically copied. I convert them to .iso files using command " affconvert -e iso <name of .aff file> "
After few minutes of process, it is converted. I can open them using engrampa but i cannot extract them. Here are other informations that probably necessary to let you guys know.

When I run " file <name of .iso file> " command, I get : 
patricia-2009-12-11.iso: DOS/MBR boot sector MS-MBR XP english at offset 0x12c "Invalid partition table" at offset 0x144 "Error loading operating system" at offset 0x163 "Missing operating system", disk signature 0xd350d350; partition 1 : ID=0x7, active, start-CHS (0x0,1,1), end-CHS (0x3ff,254,63), startsector 63, 25398702 sectors

When i try to "extract here" , i get this error : 

7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
p7zip Version 9.20 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,4 CPUs)

Processing archive: /home/nikhasan/Desktop/EvidenceFile/Patricia's devices/Computer/patricia-2009-12-11.iso

Extracting  [SYSTEM]/$MFT
Extracting  [SYSTEM]/$MFTMirr
Extracting  [SYSTEM]/$LogFile
Extracting  [SYSTEM]/$Volume
Extracting  [SYSTEM]/$AttrDef
Extracting  [SYSTEM]/.
Extracting  [SYSTEM]/$Bitmap
Extracting  [SYSTEM]/$Boot
Extracting  [SYSTEM]/$BadClus
Extracting  [SYSTEM]/$Secure:$SDS
Extracting  [SYSTEM]/$UpCase
Extracting  [SYSTEM]/$Extend
Extracting  pagefile.sys
Extracting  WINDOWS
Extracting  WINDOWS/system32
Extracting  WINDOWS/system32/config
Extracting  WINDOWS/system32/drivers
Extracting  WINDOWS/system
Extracting  WINDOWS/system32/ras
Extracting  WINDOWS/system32/spool
Extracting  WINDOWS/system32/spool/drivers
Extracting  WINDOWS/system32/spool/drivers/w32x86
Extracting  WINDOWS/system32/spool/drivers/w32x86/3
Extracting  WINDOWS/system32/spool/prtprocs
Extracting  WINDOWS/system32/spool/prtprocs/w32x86
Extracting  WINDOWS/system32/wins
Extracting  WINDOWS/system32/dhcp
Extracting  WINDOWS/repair
Extracting  WINDOWS/system32/drivers/etc
Extracting  WINDOWS/system32/drivers/disdn
Extracting  WINDOWS/inf
Extracting  WINDOWS/Help
Extracting  WINDOWS/Fonts
Extracting  WINDOWS/Config
Extracting  WINDOWS/msagent
Extracting  WINDOWS/msagent/intl
Extracting  WINDOWS/Cursors
Extracting  WINDOWS/Media
Extracting  WINDOWS/java
Extracting  WINDOWS/java/classes
Extracting  WINDOWS/java/trustlib
Extracting  WINDOWS/system32/ShellExt
Extracting  WINDOWS/Web
Extracting  WINDOWS/system32/Setup
Extracting  WINDOWS/Web/printers
Extracting  WINDOWS/system32/spool/drivers/color
Extracting  WINDOWS/system32/wbem
Extracting  WINDOWS/system32/wbem/Repository
Extracting  WINDOWS/addins
Extracting  WINDOWS/Connection Wizard
Extracting  WINDOWS/Driver Cache
Extracting  WINDOWS/Driver Cache/i386
Extracting  WINDOWS/security
Extracting  WINDOWS/security/templates
Extracting  WINDOWS/system32/npp
Extracting  WINDOWS/system32/ias
Extracting  WINDOWS/system32/dllcache
Extracting  WINDOWS/Temp
Extracting  WINDOWS/Web/printers/images
Extracting  WINDOWS/system32/export
Extracting  WINDOWS/system32/wbem/mof
Extracting  WINDOWS/system32/wbem/mof/good
Extracting  WINDOWS/system32/wbem/mof/bad
Extracting  WINDOWS/twain_32
Extracting  WINDOWS/msapps
Extracting  WINDOWS/msapps/msinfo
Extracting  WINDOWS/msagent/chars
Extracting  WINDOWS/security/logs
Extracting  WINDOWS/system32/icsxml
Extracting  WINDOWS/system32/mui
Extracting  WINDOWS/system32/mui/0009
Extracting  WINDOWS/system32/mui/dispspec
Extracting  WINDOWS/AppPatch
Extracting  WINDOWS/Debug
Extracting  WINDOWS/Debug/UserMode
Extracting  WINDOWS/system32/oobe
Extracting  WINDOWS/Help/Tours
Extracting  WINDOWS/Resources
Extracting  WINDOWS/Resources/Themes
Extracting  WINDOWS/Resources/Themes/Luna
Extracting  WINDOWS/Resources/Themes/Luna/Shell
Extracting  WINDOWS/Resources/Themes/Luna/Shell/NormalColor
Extracting  WINDOWS/system32/oobe/html
Extracting  WINDOWS/system32/oobe/html/ispsgnup
Extracting  WINDOWS/system32/oobe/html/mouse
Extracting  WINDOWS/system32/oobe/html/oemcust
Extracting  WINDOWS/system32/oobe/html/oemhw
Extracting  WINDOWS/system32/oobe/html/oemreg
Extracting  WINDOWS/system32/oobe/images
Extracting  WINDOWS/system32/oobe/setup
Extracting  WINDOWS/system32/oobe/sample
Extracting  WINDOWS/Resources/Themes/Luna/Shell/Metallic
Extracting  WINDOWS/Resources/Themes/Luna/Shell/Homestead
Extracting  WINDOWS/Help/Tours/mmTour
Extracting  WINDOWS/Help/Tours/htmlTour
Extracting  WINDOWS/Provisioning
Extracting  WINDOWS/Provisioning/Schemas
Extracting  WINDOWS/system32/1025
Extracting  WINDOWS/system32/1028
Extracting  WINDOWS/system32/1031
Extracting  WINDOWS/system32/1033
Extracting  WINDOWS/system32/1037
Extracting  WINDOWS/system32/1041
Extracting  WINDOWS/system32/1042
Extracting  WINDOWS/system32/1054
Extracting  WINDOWS/system32/2052
Extracting  WINDOWS/system32/3076
Extracting  WINDOWS/system32/wbem/xml
Extracting  WINDOWS/system32/usmt
Extracting  WINDOWS/system32/inetsrv
Extracting  WINDOWS/mui
Extracting  WINDOWS/WinSxS
Extracting  WINDOWS/WinSxS/Manifests
Extracting  WINDOWS/WinSxS/InstallTemp
Extracting  WINDOWS/ime
Extracting  WINDOWS/ime/imejp
Extracting  WINDOWS/system32/IME
Extracting  WINDOWS/system32/IME/PINTLGNT
Extracting  WINDOWS/system32/IME/CINTLGNT
Extracting  WINDOWS/system32/IME/TINTLGNT
Extracting  WINDOWS/ime/CHTIME
Extracting  WINDOWS/ime/CHTIME/Applets
Extracting  WINDOWS/ime/imejp98
Extracting  WINDOWS/ime/imejp/applets
Extracting  WINDOWS/pchealth
Extracting  WINDOWS/pchealth/helpctr
Extracting  WINDOWS/pchealth/helpctr/binaries
Extracting  WINDOWS/system32/3com_dmi
Extracting  WINDOWS/PeerNet
Extracting  WINDOWS/system32/wbem/Logs
Extracting  WINDOWS/ehome
Extracting  WINDOWS/Network Diagnostic
Extracting  WINDOWS/L2Schemas
Extracting  WINDOWS/system32/mui/0401
Extracting  WINDOWS/system32/mui/0404
Extracting  WINDOWS/system32/mui/0405
Extracting  WINDOWS/system32/mui/0406
Extracting  WINDOWS/system32/mui/0407
Extracting  WINDOWS/system32/mui/0408
Extracting  WINDOWS/system32/mui/040b
Extracting  WINDOWS/system32/mui/040C
Extracting  WINDOWS/system32/mui/040D
Extracting  WINDOWS/system32/mui/040e
Extracting  WINDOWS/system32/mui/0410
Extracting  WINDOWS/system32/mui/0411
Extracting  WINDOWS/system32/mui/0412
Extracting  WINDOWS/system32/mui/0413
Extracting  WINDOWS/system32/mui/0414
Extracting  WINDOWS/system32/mui/0415
Extracting  WINDOWS/system32/mui/0416
Extracting  WINDOWS/system32/mui/0419
Extracting  WINDOWS/system32/mui/041D
Extracting  WINDOWS/system32/mui/041f
Extracting  WINDOWS/system32/mui/0804
Extracting  WINDOWS/system32/mui/0816
Extracting  WINDOWS/system32/mui/0C0A
Extracting  WINDOWS/system32/mui/0402
Extracting  WINDOWS/system32/mui/0418
Extracting  WINDOWS/system32/mui/041a
Extracting  WINDOWS/system32/mui/041b
Extracting  WINDOWS/system32/mui/041e
Extracting  WINDOWS/system32/mui/0424
Extracting  WINDOWS/system32/mui/0425
Extracting  WINDOWS/system32/mui/0426
Extracting  WINDOWS/system32/mui/0427
Extracting  WINDOWS/system32/en
Extracting  WINDOWS/system32/scripting
Extracting  WINDOWS/system32/bootvid.dll
Extracting  WINDOWS/system32/kdcom.dll
Extracting  WINDOWS/system32/c_1252.nls
Extracting  WINDOWS/system32/c_437.nls
Extracting  WINDOWS/system32/l_intl.nls
Extracting  WINDOWS/Fonts/vgaoem.fon
Extracting  WINDOWS/system32/drivers/wmilib.sys
Extracting  WINDOWS/system32/drivers/dmload.sys
Extracting  WINDOWS/system32/drivers/ftdisk.sys
Extracting  WINDOWS/system32/drivers/ptilink.sys
Extracting  WINDOWS/system32/drivers/raspti.sys
Extracting  WINDOWS/system32/drivers/cdaudio.sys
Extracting  WINDOWS/system32/drivers/fs_rec.sys
Extracting  WINDOWS/system32/drivers/null.sys
Extracting  WINDOWS/system32/drivers/beep.sys
Extracting  WINDOWS/system32/drivers/rdpcdd.sys
Extracting  WINDOWS/system32/drivers/rasacd.sys
Extracting  WINDOWS/system32/lz32.dll
Extracting  WINDOWS/system32/olesvr32.dll
Extracting  WINDOWS/system32/olethk32.dll
Extracting  WINDOWS/system32/unicode.nls
Extracting  WINDOWS/system32/drivers/dxgthk.sys
Extracting  WINDOWS/Fonts/vgasys.fon
Extracting  WINDOWS/Fonts/vgafix.fon
Extracting  WINDOWS/system32/vga.dll
Extracting  WINDOWS/system.ini
Extracting  WINDOWS/Fonts/dosapp.fon
Extracting  WINDOWS/Fonts/ega80woa.fon
Extracting  WINDOWS/Fonts/ega40woa.fon
Extracting  WINDOWS/Fonts/cga80woa.fon
Extracting  WINDOWS/Fonts/cga40woa.fon
Extracting  WINDOWS/system32/ctype.nls
Extracting  WINDOWS/system32/kbdus.dll
Extracting  WINDOWS/Fonts/roman.fon
Extracting  WINDOWS/Fonts/script.fon
Extracting  WINDOWS/Fonts/modern.fon
Extracting  WINDOWS/Fonts/smalle.fon
Extracting  WINDOWS/Fonts/symbole.fon
Extracting  WINDOWS/Fonts/coure.fon
Extracting  WINDOWS/Fonts/sserife.fon
Extracting  WINDOWS/Fonts/serife.fon
Extracting  WINDOWS/Fonts/marlett.ttf
Extracting  WINDOWS/win.ini
Extracting  WINDOWS/system32/netevent.dll
Extracting  WINDOWS/Fonts/estre.ttf
Extracting  WINDOWS/Fonts/gautami.ttf
Extracting  WINDOWS/Fonts/latha.ttf
Extracting  WINDOWS/Fonts/mangal.ttf
Extracting  WINDOWS/Fonts/mvboli.ttf
Extracting  WINDOWS/Fonts/raavi.ttf
Extracting  WINDOWS/Fonts/shruti.ttf
Extracting  WINDOWS/system32/drivers/etc/hosts
Extracting  WINDOWS/system32/msacm32.drv
Extracting  WINDOWS/system32/drivers/parvdm.sys
Extracting  WINDOWS/system32/netmsg.dll
Extracting  WINDOWS/system32/wpa.dbl
Extracting  WINDOWS/system32/clb.dll
Extracting  WINDOWS/system32/msxmlr.dll
Extracting  WINDOWS/system32/crtdll.dll
Extracting  WINDOWS/system32/msidntld.dll
Extracting  WINDOWS/system32/mprui.dll
Extracting  WINDOWS/system32/netui2.dll
Extracting  WINDOWS/system32/dfrgres.dll
Extracting  WINDOWS/system32/net.hlp
Extracting  WINDOWS/system32/perfc009.dat
Extracting  WINDOWS/system32/perfh009.dat
Extracting  WINDOWS/system32/console.dll
Extracting  WINDOWS/Fonts/trebucbd.ttf
Extracting  WINDOWS/Fonts/arialbi.ttf
Extracting  WINDOWS/Fonts/ariali.ttf
Extracting  WINDOWS/Fonts/comicbd.ttf
Extracting  WINDOWS/Fonts/cour.ttf
Extracting  WINDOWS/Fonts/courbd.ttf
Extracting  WINDOWS/Fonts/courbi.ttf
Extracting  WINDOWS/Fonts/couri.ttf
Extracting  WINDOWS/Fonts/georgiab.ttf
Extracting  WINDOWS/Fonts/georgiai.ttf
Extracting  WINDOWS/Fonts/georgiaz.ttf
Extracting  WINDOWS/Fonts/l_10646.ttf
Extracting  WINDOWS/Fonts/lucon.ttf
Extracting  WINDOWS/Fonts/pala.ttf
Extracting  WINDOWS/Fonts/palab.ttf
Extracting  WINDOWS/Fonts/palabi.ttf
Extracting  WINDOWS/Fonts/palai.ttf
Extracting  WINDOWS/Fonts/symbol.ttf
Extracting  WINDOWS/Fonts/timesbi.ttf
Extracting  WINDOWS/Fonts/timesi.ttf
Extracting  WINDOWS/Fonts/trebucbi.ttf
Extracting  WINDOWS/Fonts/trebucit.ttf
Extracting  WINDOWS/Fonts/verdanai.ttf
Extracting  WINDOWS/Fonts/verdanaz.ttf
Extracting  WINDOWS/Fonts/webdings.ttf
Extracting  WINDOWS/Fonts/wingding.ttf
Extracting  WINDOWS/Fonts/verdanab.ttf
Extracting  WINDOWS/_default.pif
Extracting  WINDOWS/system32/12520437.cpx
Extracting  WINDOWS/system32/12520850.cpx
Extracting  WINDOWS/inf/1394.inf
Extracting  WINDOWS/inf/1394vdbg.inf
Extracting  WINDOWS/inf/61883.inf
Extracting  WINDOWS/system32/aaaamon.dll
Extracting  WINDOWS/Help/acc_dis.chm
Extracting  WINDOWS/Help/access.chm
Extracting  WINDOWS/Help/accessib.chm
Extracting  WINDOWS/inf/acerscan.inf
Extracting  WINDOWS/system32/acledit.dll
Extracting  WINDOWS/Help/aclui.chm
Extracting  WINDOWS/Help/aclui.hlp
Extracting  WINDOWS/system32/activeds.tlb
Extracting  WINDOWS/Help/addremov.chm
Extracting  WINDOWS/Help/ade.hlp
Extracting  WINDOWS/Help/admtools.chm
Extracting  WINDOWS/Help/adprop.hlp
Extracting  WINDOWS/system32/adptif.dll
Extracting  WINDOWS/system32/adsnds.dll
Extracting  WINDOWS/system32/ansi.sys
Extracting  WINDOWS/inf/apcompat.inf
Extracting  WINDOWS/system32/apcups.dll
Extracting  WINDOWS/system32/append.exe
Extracting  WINDOWS/inf/appmig.inf
Extracting  WINDOWS/inf/apps.inf
Extracting  WINDOWS/system32/arp.exe
Extracting  WINDOWS/system32/asr_ldm.exe
Extracting  WINDOWS/inf/asroc.inf
Extracting  WINDOWS/inf/atividin.inf
Extracting  WINDOWS/system32/atkctrs.dll
Extracting  WINDOWS/system32/drivers/atmepvc.sys
Extracting  WINDOWS/system32/atmpvcno.dll
Extracting  WINDOWS/system32/drivers/atmuni.sys
Extracting  WINDOWS/Help/audiocdc.hlp
Extracting  WINDOWS/Help/audit.chm
Extracting  WINDOWS/system32/autodisc.dll
Extracting  WINDOWS/inf/avc.inf
Extracting  WINDOWS/system32/avicap.dll
Extracting  WINDOWS/system32/avicap32.dll
Extracting  WINDOWS/system32/avifile.dll
Extracting  WINDOWS/inf/axant5.inf
Extracting  WINDOWS/system32/bios1.rom
Extracting  WINDOWS/system32/bios4.rom
Extracting  WINDOWS/Resources/Themes/Luna/Shell/NormalColor/shellstyle.dll
Extracting  WINDOWS/Help/blurbs.chm
Extracting  WINDOWS/Help/bnts.dll
Extracting  WINDOWS/Help/bootcons.chm
Extracting  WINDOWS/system32/bootok.exe
Extracting  WINDOWS/system32/bootvrfy.exe
Extracting  WINDOWS/Help/brief.chm
Extracting  WINDOWS/inf/brmfcmdm.inf
Extracting  WINDOWS/inf/brmfcmf.inf
Extracting  WINDOWS/inf/brmfcsto.inf
Extracting  WINDOWS/inf/brmfcumd.inf
Extracting  WINDOWS/inf/brmfcwia.inf
Extracting  WINDOWS/inf/brmfport.inf
Extracting  WINDOWS/system32/c_037.nls
Extracting  WINDOWS/system32/c_10000.nls
Extracting  WINDOWS/system32/c_10079.nls
Extracting  WINDOWS/system32/c_1026.nls
Extracting  WINDOWS/system32/c_1250.nls
Extracting  WINDOWS/system32/c_1251.nls
Extracting  WINDOWS/system32/c_1253.nls
Extracting  WINDOWS/system32/c_1254.nls
Extracting  WINDOWS/system32/c_1255.nls
Extracting  WINDOWS/system32/c_1256.nls
Extracting  WINDOWS/system32/c_1257.nls
Extracting  WINDOWS/system32/c_1258.nls
Extracting  WINDOWS/system32/c_20261.nls
Extracting  WINDOWS/system32/c_20866.nls
Extracting  WINDOWS/system32/c_20905.nls
Extracting  WINDOWS/system32/c_21866.nls
Extracting  WINDOWS/system32/c_28591.nls
Extracting  WINDOWS/system32/c_28592.nls
Extracting  WINDOWS/system32/c_28593.nls
Extracting  WINDOWS/system32/c_28598.nls
Extracting  WINDOWS/system32/c_28605.nls
Extracting  WINDOWS/system32/c_500.nls
Extracting  WINDOWS/system32/c_775.nls
Extracting  WINDOWS/system32/c_850.nls
Extracting  WINDOWS/system32/c_860.nls
Extracting  WINDOWS/system32/c_861.nls
Extracting  WINDOWS/system32/c_863.nls
Extracting  WINDOWS/system32/c_865.nls
Extracting  WINDOWS/system32/c_874.nls
Extracting  WINDOWS/system32/c_932.nls
Extracting  WINDOWS/system32/c_936.nls
Extracting  WINDOWS/system32/c_949.nls
Extracting  WINDOWS/system32/c_950.nls
Extracting  WINDOWS/inf/camdsh20.inf
Extracting  WINDOWS/Help/camera.chm
Extracting  WINDOWS/Help/camera.hlp
Extracting  WINDOWS/inf/camvid20.inf
Extracting  WINDOWS/inf/camvid30.inf
Extracting  WINDOWS/system32/cards.dll
Extracting  WINDOWS/system32/drivers/cbidf2k.sys
Extracting  WINDOWS/system32/ccfgnt.dll
Extracting  WINDOWS/Help/cdmedia.chm
Extracting  WINDOWS/Help/cdmedia.hlp
Extracting  WINDOWS/inf/certclas.inf
Extracting  WINDOWS/Help/certmgr.hlp
Extracting  WINDOWS/system32/certmgr.msc
Extracting  WINDOWS/Help/certmgr.chm
Extracting  WINDOWS/Fonts/cga40850.fon
Extracting  WINDOWS/Fonts/cga80850.fon
Extracting  WINDOWS/system32/View Channels.scf
Extracting  WINDOWS/system32/chcp.com
Extracting  WINDOWS/system32/chkdsk.exe
Extracting  WINDOWS/system32/chkntfs.exe
Extracting  WINDOWS/Help/chnscsvr.hlp
Extracting  WINDOWS/Help/chooser.hlp
Extracting  WINDOWS/system32/ciadmin.dll
Extracting  WINDOWS/Help/ciadmin.htm
Extracting  WINDOWS/system32/ciadv.msc
Extracting  WINDOWS/system32/cidaemon.exe
Extracting  WINDOWS/system32/drivers/cinemst2.sys
Extracting  WINDOWS/Help/ciquery.htm
Extracting  WINDOWS/system32/ras/cis.scp
Extracting  WINDOWS/system32/ckcnv.exe
Extracting  WINDOWS/Resources/Themes/Windows Classic.theme
Extracting  WINDOWS/system32/shellstyle.dll
Extracting  WINDOWS/system32/cliconf.chm
Extracting  WINDOWS/Help/clipbrd.chm
Extracting  WINDOWS/Help/clipbrd.hlp
Extracting  WINDOWS/Help/cmconcepts.chm
Extracting  WINDOWS/system32/cmdlib.wsc
Extracting  WINDOWS/system32/cmmgr32.hlp
Extracting  WINDOWS/system32/cmos.ram
Extracting  WINDOWS/system32/cmpbk32.dll
Extracting  WINDOWS/system32/icsxml/cmnicfg.xml
Extracting  WINDOWS/system32/cnetcfg.dll
Extracting  WINDOWS/system32/cnvfat.dll
Extracting  WINDOWS/Help/colormgt.chm
Extracting  WINDOWS/system32/comcat.dll
Extracting  WINDOWS/system32/comm.drv
Extracting  WINDOWS/system32/command.com
Extracting  WINDOWS/system32/commdlg.dll
Extracting  WINDOWS/Help/common.chm
Extracting  WINDOWS/inf/communic.inf
Extracting  WINDOWS/system32/comp.exe
Extracting  WINDOWS/system32/compact.exe
Extracting  WINDOWS/security/templates/compatws.inf
Extracting  WINDOWS/system32/compmgmt.msc
Extracting  WINDOWS/Help/compmgmt.chm
Extracting  WINDOWS/system32/compobj.dll
Extracting  WINDOWS/Help/compstui.hlp
Extracting  WINDOWS/system32/control.exe
Extracting  WINDOWS/system32/convert.exe
Extracting  WINDOWS/inf/corelist.inf
Extracting  WINDOWS/system32/country.sys
Extracting  WINDOWS/Fonts/courf.fon
Extracting  WINDOWS/Help/cpanel.chm
Extracting  WINDOWS/system32/drivers/cpqdap01.sys
Extracting  WINDOWS/Help/cscui.hlp
Extracting  WINDOWS/system32/csseqchk.dll
Extracting  WINDOWS/system32/ctl3dv2.dll
Extracting  WINDOWS/inf/cyclad-z.inf
Extracting  WINDOWS/inf/cyclom-y.inf
Extracting  WINDOWS/Help/cyycoins.chm
Extracting  WINDOWS/inf/cyyport.inf
Extracting  WINDOWS/Help/cyzcoins.chm
Extracting  WINDOWS/inf/cyzport.inf
Extracting  WINDOWS/system32/d3dim.dll
Extracting  WINDOWS/system32/d3dpmesh.dll
Extracting  WINDOWS/system32/d3drm.dll
Extracting  WINDOWS/system32/d3dxof.dll
Extracting  WINDOWS/system32/dbgeng.dll
Extracting  WINDOWS/system32/ddeml.dll
Extracting  WINDOWS/Help/ddeshare.chm
Extracting  WINDOWS/Help/ddeshare.hlp
Extracting  WINDOWS/system32/debug.exe
Extracting  WINDOWS/Help/defrag.hlp
Extracting  WINDOWS/Help/defrag.chm
Extracting  WINDOWS/system32/deskadp.dll
Extracting  WINDOWS/system32/deskmon.dll
Extracting  WINDOWS/system32/deskperf.dll
Extracting  WINDOWS/Fonts/desktop.ini
Extracting  WINDOWS/system32/devmgmt.msc
Extracting  WINDOWS/Help/devmgr.hlp
Extracting  WINDOWS/Help/devmgr.chm
Extracting  WINDOWS/Help/dfs.hlp
Extracting  WINDOWS/inf/dfrg.inf
Extracting  WINDOWS/system32/dfrg.msc
Extracting  WINDOWS/inf/dgaport.inf
Extracting  WINDOWS/inf/dgasync.inf
Extracting  WINDOWS/system32/wbem/dgnet.mof
Extracting  WINDOWS/system32/dhcpsapi.dll
Extracting  WINDOWS/system32/diactfrm.dll
Extracting  WINDOWS/Help/diagboot.chm
Extracting  WINDOWS/inf/digiasyn.inf
Extracting  WINDOWS/inf/digiisdn.inf
Extracting  WINDOWS/inf/digimps.inf
Extracting  WINDOWS/Help/digiras.chm
Extracting  WINDOWS/inf/digirp.inf
Extracting  WINDOWS/inf/digirprt.inf
Extracting  WINDOWS/Help/dijoy.hlp
Extracting  WINDOWS/system32/dimap.dll
Extracting  WINDOWS/inf/dimaps.inf
Extracting  WINDOWS/system32/diskcomp.com
Extracting  WINDOWS/system32/diskcopy.com
Extracting  WINDOWS/Help/diskmgmt.hlp
Extracting  WINDOWS/Help/diskmgmt.chm
Extracting  WINDOWS/system32/diskmgmt.msc
Extracting  WINDOWS/system32/diskperf.exe
Extracting  WINDOWS/Help/display.chm
Extracting  WINDOWS/Help/display.hlp
Extracting  WINDOWS/inf/display.inf
Extracting  WINDOWS/Help/dkconcepts.chm
Extracting  WINDOWS/system32/dllhst3g.exe
Extracting  WINDOWS/system32/dmconfig.dll
Extracting  WINDOWS/system32/dmdskres.dll
Extracting  WINDOWS/system32/dmintf.dll
Extracting  WINDOWS/system32/dmocx.dll
Extracting  WINDOWS/system32/dmview.ocx
Extracting  WINDOWS/system32/ias/dnary.mdb
Extracting  WINDOWS/system32/docprop.dll
Extracting  WINDOWS/system32/doskey.exe
Extracting  WINDOWS/inf/dot4.inf
Extracting  WINDOWS/inf/dot4prt.inf
Extracting  WINDOWS/system32/dplay.dll
Extracting  WINDOWS/system32/dpnmodem.dll
Extracting  WINDOWS/system32/dpnwsock.dll
Extracting  WINDOWS/system32/dpserial.dll
Extracting  WINDOWS/system32/dpwsock.dll
Extracting  WINDOWS/Driver Cache/i386/driver.cab
Extracting  WINDOWS/Help/drvvfp.chm
Extracting  WINDOWS/system32/drwatson.exe
Extracting  WINDOWS/Help/drwtsn32.chm
Extracting  WINDOWS/system32/drwtsn32.exe
Extracting  WINDOWS/Help/drwtsn32.hlp
Extracting  WINDOWS/system32/dsauth.dll
Extracting  WINDOWS/Help/dsclient.hlp
Extracting  WINDOWS/Help/dskquoui.hlp
Extracting  WINDOWS/system32/dsound.vxd
Extracting  WINDOWS/system32/dssec.dat
Extracting  WINDOWS/inf/dvd.inf
Extracting  WINDOWS/system32/dvdplay.exe
Extracting  WINDOWS/system32/drivers/dxapi.sys
Extracting  WINDOWS/system32/1033/dwintl.dll
Extracting  WINDOWS/system32/edlin.exe
Extracting  WINDOWS/Fonts/ega40850.fon
Extracting  WINDOWS/Fonts/ega80850.fon
Extracting  WINDOWS/Help/els.hlp
Extracting  WINDOWS/Help/els.chm
Extracting  WINDOWS/Help/encrypt.chm
Extracting  WINDOWS/inf/enum1394.inf
Extracting  WINDOWS/inf/epcfw2k.inf
Extracting  WINDOWS/inf/epsnscan.inf
Extracting  WINDOWS/inf/epsnmfp.inf
Extracting  WINDOWS/inf/epstw2k.inf
Extracting  WINDOWS/system32/esent97.dll
Extracting  WINDOWS/system32/esentprf.dll
Extracting  WINDOWS/system32/esentprf.hxx
Extracting  WINDOWS/system32/esentprf.ini
Extracting  WINDOWS/system32/esentutl.exe
Extracting  WINDOWS/Help/eudcedit.chm
Extracting  WINDOWS/Help/eudcedit.hlp
Extracting  WINDOWS/system32/eventcls.dll
Extracting  WINDOWS/system32/eventvwr.exe
Extracting  WINDOWS/system32/eventvwr.msc
Extracting  WINDOWS/system32/wbem/evntrprv.mof
Extracting  WINDOWS/Help/evntwin.hlp
Extracting  WINDOWS/system32/eventquery.vbs
Extracting  WINDOWS/system32/exe2bin.exe
Extracting  WINDOWS/system32/expand.exe
Extracting  WINDOWS/explorer.scf
Ex

It says " An error occured when extracting files. Command exited abnormally"

**Comment by raveit65** [comment]
Engrampa is a frontend which use several installed backends.
Here in fedora with p7zip-15.14.1-1.fc24.x86_64 installed i can extract an iso (fedora livecd) without any problem.
I recall that  p7zip Version 9.20 was a bit buggy.

**Comment by nikzarif** [comment]
i never did try to extract linux iso. im on my phone now so later i will inform you. however, i can extract one by one the files inside the iso except certain files ( cant really remember the name of the file ). i think its either engrampa is buggy or my os ubuntu mate is buggy. in microsoft windows, i can successfully extract them

**Comment by nikzarif** [comment]
thank you for the concern raveit65

**Comment by sc0w** [comment]
@nikzarif upgrade your system and try again

**Comment by sc0w** [comment]
@nikzarif  I close this issue for now, but feel free to reopen it whenever you experience the same bug again with your system updated
