### ISSUE TITLE
 'All files' entry is duplicated in available formats combobox

### ISSUE THREAD

**Issue by sc0w** [mate-desktop/engrampa#132]
TEST CASE:
1. Open engrampa
2. Click 'New' from toolbar
3. Expand available formats combobox

Result: duplicate entries - 'All files' and 'All Files'
Expected: one entry 'All Files'

**Comment by sc0w** [comment]
![bugengrampaallfiles](https://cloud.githubusercontent.com/assets/7734191/15267664/0745d4c4-19c8-11e6-97f1-2323280d627e.png)

**Comment by raveit65** [comment]
Confirmed!
Thank you for providing good steps to reproduce.
This makes it easier to review PRs for me.
