### ISSUE TITLE
The folder contents could not be displayed - engrampa with --default-dir and --extract

### ISSUE THREAD

**Issue by sc0w** [mate-desktop/engrampa#134]
in a terminal:

`engrampa --default-dir=./anyfolder/ --extract filecompressed
`

![bugfolderengrampa](https://cloud.githubusercontent.com/assets/7734191/15276864/31714aee-1af4-11e6-85c6-73c0613241fb.png)

**Comment by monsta** [comment]
Interesting... it behaves as if the folder didn't exist (shows the same message if you specify some non-existing folder).

**Comment by monsta** [comment]
Ok... so it expects the full URI :confused: 
```
engrampa --default-dir=file:///home/monsta/anyfolder/ --extract filecompressed
```

**Comment by zwrg** [comment]
same problem..

How can i edit thunar-archieve-plugin to add full URL to default method?
