### ISSUE TITLE
p7zip 15.14.1 breaks RAR compatibility

### ISSUE THREAD

**Issue by wine** [mate-desktop/engrampa#136]
After the upgrade of p7zip to version 15.14.1, engrampa is unable to open rar archives. I made a patch that works in my system. I hope it will be helpful.

```
diff -aur a/src/fr-command-7z.c b/src/fr-command-7z.c
--- a/src/fr-command-7z.c	2016-05-13 02:01:18.000000000 +0200
+++ b/src/fr-command-7z.c	2016-05-17 17:49:20.263092447 +0200
@@ -572,7 +572,7 @@
 		if (is_mime_type (mime_type, "application/x-rar")
 		    || is_mime_type (mime_type, "application/x-cbr"))
 		{
-			if (! check_command || g_file_test ("/usr/lib/p7zip/Codecs/Rar29.so", G_FILE_TEST_EXISTS))
+			if (! check_command || g_file_test ("/usr/lib/p7zip/Codecs/Rar29.so", G_FILE_TEST_EXISTS) || g_file_test ("/usr/lib/p7zip/Codecs/Rar.so", G_FILE_TEST_EXISTS))
 				capabilities |= FR_COMMAND_CAN_READ;
 		}
 		else
```

**Comment by cranes-bill** [comment]
Hm, this code looks bad at all... 
In my case this plugin is in `libexec` and _libdir_ is `lib64`, so patch here is a quite mandatory...

**Comment by sc0w** [comment]
It works for me

@cranes-bill actually works for you lower versions than p7zip-rar 15.14.1 ?

The actual source also verifies the /usr/lib/

**Comment by cranes-bill** [comment]
@sc0w, sorry but my English is horrible and i'm not sure does i completely understand your question...
Never mind, the patch is fine if the plugin is installed in `lib`. But i meant that the _plugin path_ should not be statically set in the source. It will be better if it uses variable which value is determined from the _configure_ script...
I'm also using `15.14.1` and it does not works until i change the path: `/usr/libexec/p7zip/Codecs/Rar.so` in my case. As i remember, it also did not worked in previous versions.

**Comment by monsta** [comment]
Huh... but that means file-roller would fail this check on your system as well... Can you try it for a test?

**Comment by sc0w** [comment]
yes, file-roller have this same bug

what do you think about this?

```patch
diff --git a/src/fr-command-7z.c b/src/fr-command-7z.c
index 316df11..f516db6 100644
--- a/src/fr-command-7z.c
+++ b/src/fr-command-7z.c
@@ -572,7 +572,8 @@ fr_command_7z_get_capabilities (FrCommand  *comm,
 		if (is_mime_type (mime_type, "application/x-rar")
 		    || is_mime_type (mime_type, "application/x-cbr"))
 		{
-			if (! check_command || g_file_test ("/usr/lib/p7zip/Codecs/Rar29.so", G_FILE_TEST_EXISTS))
+			if (! check_command || g_file_test ("/usr/lib/p7zip/Codecs/Rar29.so", G_FILE_TEST_EXISTS) || g_file_test ("/usr/lib/p7zip/Codecs/Rar.so", G_FILE_TEST_EXISTS)
+			    || g_file_test ("/usr/libexec/p7zip/Codecs/Rar29.so", G_FILE_TEST_EXISTS) || g_file_test ("/usr/libexec/p7zip/Codecs/Rar.so", G_FILE_TEST_EXISTS))
 				capabilities |= FR_COMMAND_CAN_READ;
 		}
 		else

**Comment by cranes-bill** [comment]
This probably will work (i will test later), but there is some systems where the plugin is installed in `/usr/lib64/p7zip/Codecs/`, so i thought for something as follow to be add in _configure.ac_, but i'm not familiar with **autotools** macros:
```
for plugin in {Rar29.so,Rar.so}; do 
    test_rar_plugin=`locate $plugin`
AC_DEFINE (variable, $test_rar_plugin, [description])
..........
```

**Comment by raveit65** [comment]
Good that fedora is painless :wink: 
http://pkgs.fedoraproject.org/cgit/rpms/p7zip.git/tree/p7zip_15.14-norar_cmake.patch

**Comment by raveit65** [comment]
Seems that p7zip rar have a licence problem.
http://pkgs.fedoraproject.org/cgit/rpms/p7zip.git/commit/?h=f24&id=b95b5a0811a197a96043373e1ae9b3ad9745e699

**Comment by cranes-bill** [comment]
@sc0w, as i guessed, your patch is working.
As mine as well :stuck_out_tongue_winking_eye: :
```diff
diff --git a/engrampa.orig/configure.ac b/engrampa/configure.ac
index 99616a1..87cb40c 100644
--- a/engrampa.orig/configure.ac
+++ b/engrampa/configure.ac
@@ -185,6 +185,15 @@ fi
 
 dnl ******************************
 
+set_rar_plugin="/usr/lib/p7zip/Codecs/Rar29.so"
+for plugname in {Rar29.so,Rar.so}; do 
+    locate_plugin=`locate $plugname`
+if test -n "$locate_plugin" ; then
+set_rar_plugin="$locate_plugin"
+fi
+done
+  AC_DEFINE_UNQUOTED(SEVEN_ZIP_PLUGIN, "${set_rar_plugin}", [Define 7zip's rar plugin path])
+
 dnl ******************************
 
 AC_ARG_ENABLE([magic],
diff --git a/engrampa.orig/src/fr-command-7z.c b/engrampa/src/fr-command-7z.c
index 316df11..a643eb5 100644
--- a/engrampa.orig/src/fr-command-7z.c
+++ b/engrampa/src/fr-command-7z.c
@@ -572,7 +572,7 @@ fr_command_7z_get_capabilities (FrCommand  *comm,
 		if (is_mime_type (mime_type, "application/x-rar")
 		    || is_mime_type (mime_type, "application/x-cbr"))
 		{
-			if (! check_command || g_file_test ("/usr/lib/p7zip/Codecs/Rar29.so", G_FILE_TEST_EXISTS))
+			if (! check_command || g_file_test (SEVEN_ZIP_PLUGIN, G_FILE_TEST_EXISTS))
 				capabilities |= FR_COMMAND_CAN_READ;
 		}
 		else
```

**Comment by sc0w** [comment]
@cranes-bill your patch fails if the user doesnt have installed the command locate

**Comment by cranes-bill** [comment]
Ooops, it always was installed by default to me, so i thought it's in **coreutils** package... :neutral_face:
What about if add a check for _locate_?

**Comment by sc0w** [comment]
anyway, using configure.ac, your patch always fails in this case:

1) I dont have p7zip-rar installed

2) I install engrampa with your patch

3) I install p7zip-rar

4) I run engrampa, and your patch don't works

**Comment by cranes-bill** [comment]
Because i made it to set `Rar29` in case that plugin missing.
Never mind...
