### ISSUE TITLE
Gtk-WARNING **: GtkScrolledWindow and gtk_widget_get_preferred_width/height()

### ISSUE THREAD

**Issue by sc0w** [mate-desktop/engrampa#144]
loading engrampa in a terminal: 

$ engrampa file.zip

**(engrampa:5145): Gtk-WARNING **: Allocating size to GtkScrolledWindow 0x55cc6a1542c0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?**

**Comment by raveit65** [comment]
Normal warning with gtk+-3.20 :smile: 
You get this with mostly every package.

**Comment by sc0w** [comment]
ok thanks :)
