### ISSUE TITLE
engrampa can't open ".war" format

### ISSUE THREAD

**Issue by sc0w** [mate-desktop/engrampa#145]
engrampa should be able to open .war files

file-roller without libarchive can open

https://bugs.launchpad.net/ubuntu/+source/file-roller/+bug/877256/+attachment/2559339/+files/sample.war

**Comment by ianmcxa** [comment]
I have no problems opening the .war file in Engrampa 1.12.0. What version are you using?

**Comment by sc0w** [comment]
thanks for the info

it's strange

I can't open the file with 1.12 and the latest version, but it works on file-roller

I can open it in a virtual machine
