### ISSUE TITLE
engrampa show the folder containing the archive

### ISSUE THREAD

**Issue by patatetom** [mate-desktop/engrampa#147]
hi,

strange behavior for some time now...

_$ zip /tmp/test.zip /home/me/Flask.*
  adding: home/me/Flask.0.10.pdf (deflated 3%)
  adding: home/me/Flask.0.11.pdf (deflated 3%)_

_$ engrampa /tmp/test.zip
(engrampa:1348): Gtk-WARNING **: Allocating size to GtkScrolledWindow 0x15b22c0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?_
![2016 08 04-09 40 44](https://cloud.githubusercontent.com/assets/14196171/17394119/bdf5e53e-5a27-11e6-8883-39b6520c5499.png)

I'm on ArchLinux with OpenBox as desktop manager and Engrampa is version 1.12.0.

regards.

**Comment by sc0w** [comment]
I think your problem was fixed in https://github.com/mate-desktop/engrampa/commit/4f65bde8fc4d4efe747d4e7fbeba1211469ed79a

Can you try with engrampa 1.14 ?

**Comment by monsta** [comment]
Weird... Arch, as a rolling release, should already have the latest MATE (1.14) available...

**Comment by sc0w** [comment]
Solved in https://github.com/mate-desktop/engrampa/commit/4f65bde8fc4d4efe747d4e7fbeba1211469ed79a

**Comment by patatetom** [comment]
hi,
the new version 1.14.1 seems to slolve the problem : thanks :-)
regards
