### ISSUE TITLE
Can't create ZIP archive when p7zip is installed in OS

### ISSUE THREAD

**Issue by TomaszGasior** [mate-desktop/engrampa#153]
I use Manjaro Linux 16.08 with XFCE desktop environment. 
If I have installed p7zip in my OS, I can create 7z archive by Engrampa, but I can't create ZIP archive. When I try, Engrampa shows error „Error encountered during adding files to archive” (translated from Polish). I can read ZIP files, but I can't create new.
When I remove p7zip from OS, 7z option disappears in Engrampa, but I can create ZIP archive successfully. 

This problem does not exits in File Roller from Manjaro's repository.

**Comment by sc0w** [comment]
I can do it

p7zip version?

engrampa version?

**Comment by TomaszGasior** [comment]
Engrampa — 1.14.1 GTK2
p7zip — 16.02 2016-05-21

**Comment by sc0w** [comment]
I have tested with engrampa 1.14.1 gtk2 and p7zip 16.02, and I can create zip files

**Comment by TomaszGasior** [comment]
What distribution you use?

**Comment by sc0w** [comment]
debian testing

**Comment by TomaszGasior** [comment]
Problem still exists.
Can someone test Engrampa behavior on Manjaro Linux?

**Comment by TomaszGasior** [comment]
I do not know, where was problem but I solved it. 
I installed Dconf Editor and I recursively restored settings to default in path:
/org/mate/engrampa/

It seems to me problem was in incompatibility with settings options during Engrampa updates, but I can't prove it.

**Comment by sc0w** [comment]
ok, good to know
