### ISSUE TITLE
gtk 3.21.5 - dialog for creating new archive

### ISSUE THREAD

**Issue by sc0w** [mate-desktop/engrampa#154]
**Archive -> New**

See the diferences:

**gtk 3.16.6** engrampa 1.14.1

I can see **other options**, and the **scroll bar**

![3 16 6engrampa](https://cloud.githubusercontent.com/assets/7734191/18603771/ad3c7a18-7c74-11e6-82bc-7ad1252948d6.png)

**gtk 3.21.5** engrampa 1.14.1

where is the **other options**, and the **scroll bar**?

![3 21 5engrampa](https://cloud.githubusercontent.com/assets/7734191/18603781/b732f524-7c74-11e6-9dd2-7c77b0399646.png)

With the latest version in the master branch, same problem, there is no scroll bar

@monsta @raveit65 @lukefromdc

can you confirm this?

**Comment by lukefromdc** [comment]
I have the "other options", the scrollbar, and the expander showing just fine
in my own theme-and in all of the MATE themes. I have engrampa from current
master, possibly one of the deprecation fixes made the difference?

**Comment by raveit65** [comment]
I can confirm, with engrampa build from latest master and gtk+-3.21.5, i have the expander 'other options' only if i resize the window.
Increasing the window size shows the expander and reducing the window size sends the expander in a blackhole ;)
The srollbar is never there. 
Note, the expander was part of GtkGrid port, but the whole window is dialog-open from gtk+.

Same package of engrampa build against gtk+-3.20 works fine.
Looks like that gtk+-3.21/22 becomes one of the poorest version ever.

**Comment by raveit65** [comment]
But if i close the 'file format' expander the expander 'other options' is there.
So i think it is a problem with the scrollbar in the  'file format' expander, which was never touched with latest commits.

**Comment by lukefromdc** [comment]
GTK 3.22 is also going to be the last version of GTK3, meaning over time
all distros will end up using it same as there is now only one GTK2 version
anyone uses. They really should have stopped at GTK 3.20 or 3.18 and
branched GTK4 after that.  As it stands probably a lot of distros that use
GTK 3.22 will have issues with a lot of apps in their first cycle to use it, 
hope nobody ends up with their first GTK 3.22 versions of anything in an 
LTS.

**Comment by lukefromdc** [comment]
I don't have to resize the window to get it on my systems for some reason,
used GTK 3.21.6 from git master pull Sep 16 in these tests.

**Comment by raveit65** [comment]
After updating f25 to released GTK 3.21.6 the issue is gone.
Scrollbar and  the expander 'other options' are there.

**Comment by sc0w** [comment]
It seems to be fine with gtk 3.21.6 :)
