### ISSUE TITLE
Amiga compressed LHA archives 

### ISSUE THREAD

**Issue by telanus** [mate-desktop/engrampa#155]
when you open an Amiga compressed archive like: http://aminet.net/game/actio/WormWars.lha engrampa crashes.

ran engrampa WormWars.lha and it says segmentation fault

**Comment by sc0w** [comment]
same bug on file-roller

I have tested with **lhasa 0.3.1**

**Comment by sc0w** [comment]
@telanus another .lha files work for you?

**Comment by telanus** [comment]
I've tried these: ftp://ftp.amigascne.org/mirrors/ftp.modland.com/pub/trackers/Amiga/Protracker/ and those it open

tested a  bit further tonight (just quickly) and it seems those lha archives created on an Amiga with OS 3.x and 4 will not open, but MorphOS and up those work
