### ISSUE TITLE
.war archives with mime-type x-webarchive are unsupported

### ISSUE THREAD

**Issue by maxzhilin** [mate-desktop/engrampa#157]
.war files created by ant have mime-type application/x-webarchive - looks like only those with application/x-war are currently supported in 1.16.0. Included patch with added mime-type.
[war.txt](https://github.com/mate-desktop/engrampa/files/545601/war.txt)

**Comment by sc0w** [comment]
hello, you can see https://github.com/mate-desktop/engrampa/issues/145

I can't open:

https://bugs.launchpad.net/ubuntu/+source/file-roller/+bug/877256/+attachment/2559339/+files/sample.war

the file is application/x-webarchive

your patch don't works for me

**Comment by maxzhilin** [comment]
That's odd,  I have checked with that file and seems to be working for me - maybe I created the patch incorrectly...

![screenshot from 2016-10-22 23-58-40](https://cloud.githubusercontent.com/assets/22992594/19624610/92a25b54-98b3-11e6-8977-31ec0cfe87ad.png)

**Comment by sc0w** [comment]
the file works for you without the patch?

**Comment by cranes-bill** [comment]
The file is **ZIP**......

**Comment by maxzhilin** [comment]
@sc0w - the file doesn't work without the patch and testing working after. The only change I have made is to add the x-webarchive to fr-init.c. I've also added this mime type to the desktop icon entries, but this is not included in the patch.

@cranes-bill - are you referring to the sample.war? Not sure how this is zip file.

**Comment by cranes-bill** [comment]
@maxzhilin yes, [sample.war](https://bugs.launchpad.net/ubuntu/+source/file-roller/+bug/877256/+attachment/2559339/+files/sample.war) is a **ZIP** file!

![capture du 2016-10-23 20-35-00](https://cloud.githubusercontent.com/assets/5161278/19628187/c4bdb644-9960-11e6-960f-635e49466301.png)

**Comment by maxzhilin** [comment]
This is interesting - I tried downloading the sample file in Chrome and i get application/x-webarchive. Downloading with wget it give me application/zip.

Anyways, .war created with ant are given x-webarchive mime type and this should be supported 

![screenshot from 2016-10-23 11-09-29](https://cloud.githubusercontent.com/assets/22992594/19628407/e789566e-9911-11e6-8fc7-3e7aa20de05a.png)

**Comment by sc0w** [comment]
I see like @maxzhilin 

anyway, if I rename **sample.war** to **sample.zip** or **sample.7z** engrampa can open it

Can someone give us another .war file with mime-type x-webarchive ?

**Comment by sc0w** [comment]
@maxzhilin can you give us some file created by ant?

**Comment by maxzhilin** [comment]
I found a sample project here: https://dzone.com/tutorials/java/ant/ant-sample-build-file-war-1.html
Here is the war file output: https://1drv.ms/u/s!ArSCcenVflGZgqgws4fx4I2hBJBsZw

**Comment by sc0w** [comment]
@maxzhilin 

It works for me if I add something like this on fr-init:

	{ "application/zip",                    ".war",      N_("Zip (.war)"), 0 },

and later...

	{ ".war", "application/zip" },

my solution works for you?

**Comment by sc0w** [comment]
I have a better solution, and the icon...

@maxzhilin 
> I've also added this mime type to the desktop icon entries, but this is not included in the patch.

how can i do?
