### ISSUE TITLE
gzip: stdin: not in gzip format ERROR

### ISSUE THREAD

**Issue by Yanpas** [mate-desktop/engrampa#158]
This error happens when I open this archive 
[snmp++-3.3.7.tar.gz](https://github.com/mate-desktop/engrampa/files/659002/snmp.-3.3.7.tar.gz)
Xarchiver opens this file ok. Engrampa 1.14

**Comment by cranes-bill** [comment]
This file is a _**TAR**_, but not a **_GZIP_** archive.

**Comment by Yanpas** [comment]
Oh, my fault
