### ISSUE TITLE
Cannot display Chinese file names(gb2312 encoded)

### ISSUE THREAD

**Issue by jinguojie-loongson** [mate-desktop/engrampa#160]
To reproduce this issue:

- Under Windows XP(Chinese simplified edition), create a .zip file which contains a Chinese file name.
 Any compress tool can be used, like WinRAR.
- Copy the zip file to Fedora25
- Login into Fedora 25 with Mate session and zh_CN.UTF-8 language.
- Double click the zip file
- The Chinese file name is displayed incorrectly.

**Comment by monsta** [comment]
Yes, it's a problem with p7zip, reported in https://github.com/mate-desktop/engrampa/issues/102. Please leave your comments there (and post your p7zip version just in case).
