### ISSUE TITLE
Wrong behavior of Skip button in Replace file dialog

### ISSUE THREAD

**Issue by honza889** [mate-desktop/engrampa#161]
Button **Skip** in "Replace file?" dialog extract whole archive instead of skipping one file.

Version: engrampa-**1.16.0**-1.fc25.x86_64
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1422004

1. Prepare ZIP archive containing files A and B and blank directory containing A
2. Open archive using engrampa
3. Drag A to directory - dialog Replace file "A"? will show
5. Press Skip button

**Actual results:**
File A from directory is replaced by file A from archive and file B is extracted too - directory now contain files A and B from archive.

**Expected results:**
In directory should be original file A only. (no file B)

**Comment by sc0w** [comment]
thanks for your report

confirmed

**Comment by sc0w** [comment]
If the file is inside a folder (in the compressed file) the skip button works as expected

**Comment by sc0w** [comment]
in the code:

https://github.com/mate-desktop/engrampa/blob/master/src/fr-window.c#L6653

https://github.com/mate-desktop/engrampa/blob/master/src/fr-window.c#L6777

https://github.com/mate-desktop/engrampa/blob/master/src/fr-window.c#L6695

**Comment by sc0w** [comment]
**file-roller:**

with 3.6.0 works well, and it is reproducible in 3.5.91
