### ISSUE TITLE
wrong date modified shown in column when using unrar as lib

### ISSUE THREAD

**Issue by kn00tcn** [mate-desktop/engrampa#163]
i probably should have mentioned this almost a year ago when i first started using linux

(these are some examples, 'turns into' is engrampa's column, i'll rename the day-month-year it uses so it's easier to see)
`2007-06-04` turns into `2009-11-28`
`2012-09-19` turns into `2025-03-04`
`2013-09-20` turns into `2026-03-06`
`2013-09-21` turns into `2027-03-06`
`2014-07-07` turns into `2013-01-03`
`2014-07-10` turns into `2016-01-04`

it looks like the similar dates show identical year differences, that must be the clue we need

the files are rar version 4 & 5, dont think i've checked version 3, the hours:minutes might be fine

using the 'last output' option shows the correct date, as does commandline unrar, so unrar itself seems to be fine

the extracted files also have the correct date, & it's correct when switching to unarchiver (coincidentally i now found a bug in unarchiver right as i started testing, it takes a min to scan a specific archive, but not other ones, so it would be nice to use the official unrar)

**Comment by sc0w** [comment]
with `rar l thefilename.rar` the date is correct

with `engrampa` and `file-roller` with `rar` is wrong

`engrampa` with `unar` shows the date correctly

this needs some investigation

confirmed

**Comment by kn00tcn** [comment]
ah yes, i did try gnome's archive viewer many months ago, same issue, at the time i assumed it was rar's fault but never checked what it outputs until now

https://github.com/GNOME/gnome-autoar/commit/66cf03f9f1913bc908fea56afbdf984e1a2c18d6 funny

also tried xarchiver now, nothing shows up when opening rars even though it says it's supported

...ok i held off on posting this reply until i searched the code

https://github.com/mate-desktop/engrampa/blob/master/src/fr-command-rar.c line 72, it seems to be doing day-month-year instead of year-month-date

i am not set up to compile & test, can i still make a pull request for someone else to test?

**Comment by sc0w** [comment]
> ah yes, i did try gnome's archive viewer many months ago, same issue, at the time i assumed it was rar's fault but never checked what it outputs until now

the rar commandline works fine, with `rar l filearchive.rar` I can see the real date

> GNOME/gnome-autoar@66cf03f funny

engrampa doesn't support libarchive

> also tried xarchiver now, nothing shows up when opening rars even though it says it's supported

I can't open rar files with xarchiver and rar installed, I tried with xarchiver 0.5.4

> i am not set up to compile & test, can i still make a pull request for someone else to test?

yes

> i scrolled down to the 'sample output', just seems so obsolete... but now i'm thinking, should we handle people using old versions of unrar? will the code change now flip unarchiver's output?

- with engrampa, on the menu **View -> Last output** I can see the real date using rar (non free)

- The old versions? I don't know, if the "old version" is since long time ago, we can drop it, I think

- unarchiver have different code and the date works fine: https://github.com/mate-desktop/engrampa/blob/master/src/fr-command-unarchiver.c

**Comment by kn00tcn** [comment]
if i'm understanding the code, there are rar4 checks? if we permanently change the date order, that means rar4 will now be wrong, so maybe we should alert the user to update their binary if rar4 is detected?

**Comment by sc0w** [comment]
I answered you in your PR

**Comment by sc0w** [comment]
merged: https://github.com/mate-desktop/engrampa/commit/e1646ec8dc32fe55fc610c7a17cf6c128a0827cc

**Comment by damufo** [comment]
I reopen this thread.
I have same issue with .7z and zip
Engrampa 1.26.2
Debian 13
Xfce

Date modification is distinct after, when extract.

<img width="1227" height="323" alt="Image" src="https://github.com/user-attachments/assets/b68986e3-4f53-41c8-89c1-c9b7b018dd4c" />

<img width="1204" height="351" alt="Image" src="https://github.com/user-attachments/assets/5db5cbde-e574-45a6-9a01-668e4967d93e" />

**Comment by vkareh** [comment]
This is not the same bug. The original was for the date parsing order, which meant that things like the day was interpreted as the year and so on. In your case it seems like the dates are off by one hour, which means the parsing is correct, but there's a timezone/DST issue somewhere (could be engrampa or could be your setup).

Can you reproduce this in file-roller (or `unzip`?) as well or is this an issue *only* in engrampa?

**Comment by damufo** [comment]
File-roller has same date that Engrampa.

<img width="1098" height="639" alt="Image" src="https://github.com/user-attachments/assets/3e0468a9-82db-41ac-a0d9-01e42b2d737b" />

**Comment by vkareh** [comment]
Yeah to me this sounds like something specific to your setup...
does it happen with all files or just with some files? I'm wondering if the issue is specifically your computer clock settings or if it's some internal attribute in your file that's causing this.

In either case, this doesn't seem like a bug in engrampa, but some quirk of how the date is handled locally in your setup.

**Comment by damufo** [comment]
OK, this is a issue of any archives.
I attach a example if you need test this.

[example.zip](https://github.com/user-attachments/files/29897190/example.zip)

<img width="881" height="351" alt="Image" src="https://github.com/user-attachments/assets/46e3d5b3-4ebb-4cfb-8f55-41920b8641d1" />

**Comment by vkareh** [comment]
Okay, I was able to reproduce with that file, but zipping my own shows up correctly.
In fact, I opened a random zip file I had and different files had different offsets.

What this suggests is that engrampa may be doing some locale/timezone conversion that's different than what the file manager shows directly. Maybe it's worth exploring. Do you mind opening a separate ticket with this info?
