### ISSUE TITLE
Add support to unpack .mmpz and .mmp sample files made for LMMS

### ISSUE THREAD

**Issue by Umeaboy** [mate-desktop/engrampa#169]
Let me start by saying that I use Linux.
I went to Youtube to look for some tutorials on how to make a song in LMMS and that's when I found this video ( https://www.youtube.com/watch?v=68kUfAsN1nI ). I know that the user is in Windows to extract this file, but I'm looking to see if Engrampa can get support to unpack that file in the near future for us Linux users when it comes to LMMS projects.

All I see when trying to open the file with Engrampa is an error saying:

Could not open "itsdone.mmp"

The archive type is not supported.

I went to google to look for a way to extract the file and this thread on the Linux Musicians forum told me to use unzip which gave me this as a resulting error:

Archive:  itsdone.mmpz
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of itsdone.mmpz or
        itsdone.mmpz.zip, and cannot find itsdone.mmpz.ZIP, period.
I therefor used lmms to upgrade the mmpz to a mmp file to try to extract it again, but I got the same result with Engrampa even with that file type.

I'm currently using Cinnamon 3.2.2 as a main Desktop Environment and the Engrampa version is 1.18.0 and the Unzip version is 6.0.

**Comment by sc0w** [comment]
are you sure **mppz** is a compressed file?

I tried with some files in https://lmms.io/lsp/

and I can't open with unzip, 7z, unar, rar... seems only lmms can open it

**Comment by Umeaboy** [comment]
https://linuxmusicians.com/viewtopic.php?t=2602

Well, the guy uses the file explorer to extract that file so yes I'd assume that it's compressed.

**Comment by monsta** [comment]
Engrampa is just UI for various archive tools. If some app creates non-standard zip files, and common archive tools like 7z or unzip can't read them, it's not for us to fix. You'd get the same result with file-roller for example.
