### ISSUE TITLE
"View All Files" view-trying to delete selected folder or folders deletes everything in archive

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/engrampa#172]
If and only if the "view all files" option for Engrampa is selected, the delete dialog gives the option to delete selected files, which works fine for files but if a directory is selected, both all directories and all files in the toplevel directory are deleted. What remains is an empty archive.

**Comment by sc0w** [comment]
I can't reproduce this issue, someone can confirm it ?

**Comment by lukefromdc** [comment]
Maybe a version issue? I am using MATE 1.19 from git master, engrampa included. All of it built over GTK 3.22.12 at this point. OS is Debian Unstable

**Comment by lukefromdc** [comment]
I just found that this delete issue is limited to the "View All Files" view and does not occur in the default "View As a Folder" interface

**Comment by sc0w** [comment]
It works as expected for me, with "view all files", I can see all the files, and if I delete one folder only the files in that folder will be removed

**Comment by raveit65** [comment]
I can't confirm this with "view all files" or "show as folder" option.
With using the "choose file" option in delete-dialog only the selected folder will be deleted.
I think the "view all files" option doesn't make any different where a file is stored, in result you see all files and the including folder at the same level in this view.
Ok course all files in the folder will delete if you delete the folder.
Deleting an empty folder remove any other file here.
...but maybe i do not understand the issue here...........

**Comment by lukefromdc** [comment]
Must be some difference between our builds or systems. Once again, I opened a copy of a .zip file, set Engrampa to view as a folder, went into that folder, deleted one folder within it with no problem. Then set Engrampa to view all files, tried to delete one folder, and everything in the archive was deleted. This is nasty, but apparently does not happen in all setups by your report. Can anyone else duplicate this?

**Comment by sc0w** [comment]
I attached a video here and the zip file used in the video

[out-25.ogv.zip](https://github.com/mate-desktop/engrampa/files/970661/out-25.ogv.zip)

[untitled.zip](https://github.com/mate-desktop/engrampa/files/970662/untitled.zip)

**Comment by lukefromdc** [comment]
you have exactly one directory in that test file, and indeed engrampa works as it should, deleting only that one selected directory. My tests all had multiple included directories in the tarball, that might be the difference. In those tarballs, deleting one of the multiple directories deleted all of them, plus all other files. With your one directory plus some files tarball, deleting the directory deleted only that directory and its contents, nothing else.

**Comment by raveit65** [comment]
Can you please provide such a tarball for reproducing?

**Comment by lukefromdc** [comment]
I used a copy of the mate-polkit-dev-deprecations tarball for my tests. 

I then checked against the possibiliy that I was just deleting the toplevel directory by adding a second folder to it alongside the toplevel directory-and it STILL deleted everything in both of those directories if any folder in any directory was deleted. On still further testing, I found this is a bit complex: I took a folder containing other folders and copied it, so there were two toplevel directories inside. I could delete either toplevel directory, and all of its files would disappear without harming the other toplevel directory or anything inside it. Deleting any normal file also worked. What did not work was trying to delete any folder contained within either toplevel directory, which would also delete everything in that toplevel and everything else in the tarball including the other toplevel directory.

**Comment by sc0w** [comment]
seems the "delete selected files" is only supported in master folders

another file for testing:

[testagain.zip](https://github.com/mate-desktop/engrampa/files/971825/testagain.zip)

folder **a** with the subfolders **a1** **a2** **a3**

folder **b** with the subfolders **b1** **b2** **b3**

if we try to delete (with view all files) **a1**, **a2**, **a3**, **b1**, **b2** or **b3** we see this:

![allfiles](https://cloud.githubusercontent.com/assets/7734191/25636541/f9ebc024-2f81-11e7-8923-dde53d899769.png)

there is no **selected files** option

so, if we click **Delete**, we asume **all files** will be deleted

and, if we try to delete folders **a** or **b** , master folders, it can be deleted and we see:

![seledtedfiles](https://cloud.githubusercontent.com/assets/7734191/25636627/464912be-2f82-11e7-9463-bc17fa6cf03a.png)

and only the folder/files in that folder will be deleted

**Comment by raveit65** [comment]
yes. i see the same weirdness with deleting a locale (it) folder from engrampa tarball.
![engrampa-delete](https://cloud.githubusercontent.com/assets/961604/25637363/065746fa-2f85-11e7-8466-ffc093d70faf.png)
Pressing the button delete all files.

**Comment by lukefromdc** [comment]
The actual problem is this: in some cases, by clicking around selecting and deselecting folder it's possible to get the "selected folder" option active and checked, only to find that it is not actually used and all files and folders are deleted. Thus there is some kind of issue with the GUI, which should never activate that radio button when it is not going to work. Alternate would be for selecting a folder to always be supported, probably more difficult.

**Comment by sc0w** [comment]
file-roller 3.22.3 have the same behavior

**Comment by sc0w** [comment]
we really need folders in "view all files" ?

@raveit65 @lukefromdc 
what do you think with the "view all files", only with files without folders?

we can order that files by location, and the look is more clear

**Comment by lukefromdc** [comment]
Seems a good idea not to show the folders if all the files are already being laid out, as it is NOT obvious what is in each folder, nor what is deleted by deleting a folder. Certainly fixes this issue as well.

**Comment by sc0w** [comment]
you can see the folder in the column **locations**

capture with this feature

![samplefeature](https://cloud.githubusercontent.com/assets/7734191/25682882/1ef2885c-305a-11e7-97ec-e1108e6ceb82.png)

I suppose this is a crazy idea, probably some users don't like this, but is good the option to enable this feature :)

**Comment by raveit65** [comment]
As the name of the view is "view all files", viewing folders there is wrong imo.
Especially we have a 'deleting folder' bug here.
And the structur of the archive you see in location column header or you can enable the sidebar.
So, i am fine with it.
Users will always complain about a change, but in this case we have a reason to do that.

**Comment by raveit65** [comment]
Hmm, after writing the review i **closed** engrampa and i got a abrt alarm with a stacktrace.
But i don't see that it is relvant to the PR.
https://www.dropbox.com/s/oegp3lujw6mrqn9/engrampa-backtrace?dl=0
Hopefully only a coincidence.

**Comment by lukefromdc** [comment]
I tested this, worked fine and didn't get any nasties in terminal on closing a test instance.

**Comment by sc0w** [comment]
engrampa closes normally here, anyway, I will keep the PR opened some days, to make sure there is no problem
