### ISSUE TITLE
Cannot use absolute pathnames for this command (7zip on zip-archive)

### ISSUE THREAD

**Issue by schmittm** [mate-desktop/engrampa#18]
I have a normal zip-archive with files and folders in it, trying to drag'n'drop just ONE file to caja leads to the following message in a box:

7-Zip 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
p7zip Version 9.20 (locale=de_DE.UTF-8,Utf16=on,HugeFiles=on,2 CPUs)

Error:
Cannot use absolute pathnames for this command

First, why 7zip if unzip seems to be the better match anyway? And second... somehow engrampa has an issue with the command syntax of 7zip I think which leads to this error message under some circumstances. Decompression works if the error was not shown before and if for example the whole archive is decpmpressed without drag'n'drop..

**Comment by sc0w** [comment]
here is the bug in 7z and a file for testing:

http://sourceforge.net/p/p7zip/bugs/71/

**Comment by sc0w** [comment]
I testing with p7zip 9.20 and 9.38

The bug is on 9.20

With 9.38 engrampa works perfectly

**Comment by monsta** [comment]
Is there some kind of workaround we can use for 9.20?

**Comment by sc0w** [comment]
file-roller without libarchive works with p7zip 9.20 and that file

[0131427E_F1.zip](https://github.com/mate-desktop/engrampa/files/300098/0131427E_F1.zip)

**Comment by sc0w** [comment]
at this time, I think there is no reason to support p7zip 9.20, engrampa works fine with latest versions, so this issue can be closed
