### ISSUE TITLE
Error while creating/editing ZIP archives

### ISSUE THREAD

**Issue by TomaszGasior** [mate-desktop/engrampa#181]
#### Actual behaviour

When `/org/mate/engrampa/general/compression-level` setting in dconf is set to "maximum" Engrampa does not create ZIP archives. When you try to add file to new or existing ZIP archive, Engrampa shows message "An error occurred while adding files to the archive.".
If you reset following setting to default "normal" value, problem disappears.

#### Package version
engrampa 1.18.2

#### Linux Distribution
Arch linux

**Comment by sc0w** [comment]
It was already solved in https://github.com/mate-desktop/engrampa/commit/7ba30abc3387cd0c6615475fdd7617426bac8fc3

@raveit65 @monsta it is time to the next 1.18 release?

**Comment by raveit65** [comment]
For one commit?
Another solution is that reporter filed out a distro report and ask maintainer to use this commit as patch for the while.
