### ISSUE TITLE
"Archive > New" window, unneeded margins.

### ISSUE THREAD

**Issue by TomaszGasior** [mate-desktop/engrampa#184]
#### Expected behaviour
Engrampa's file chooser does not match native gtk file chooser.

#### Actual behaviour
Window for creating new archive uses margins. It should not use margins to match gtk file chooser appearance. 

#### Steps to reproduce the behaviour
Just go to menubar, Archive -> New. 

See screenshot. Engrampa's "New" window on the left side, standard file chooser on the right side.
https://i.imgur.com/FvLsMbQ.png

#### Package version
engrampa 1.18.2-1

#### Linux Distribution
Manjaro

**Comment by kn00tcn** [comment]
ooh nice spot, open & extract dont do this, maybe i'll try to figure this out

**Comment by raveit65** [comment]
I do not get why it is bad to use a margin.
It is simple a question of design.
For me it looks bad without the margin :)
