### ISSUE TITLE
delete files in a encrypted archive

### ISSUE THREAD

**Issue by mirkander** [mate-desktop/engrampa#185]
#### Expected behaviour
Delete or rename files inside encrypted archive (rar o 7z) created selecting "encrypt the file list too" option.

#### Actual behaviour
Engrampa doesn't do it.

#### MATE general version
1.18

#### Package version
1.18.2-1

#### Linux Distribution
Linux mint mate 18.2

**Comment by monsta** [comment]
Fix for 7z is released in version 1.18.3. Fix for rar will be done later. If you know any other types of archives where this issue should be fixed, please post them here.

**Comment by sc0w** [comment]
rename files in 7z without the list encrypted is fixed here: https://github.com/mate-desktop/engrampa/commit/516bd1a9d6003711b0ba42e3dcd233997f6cf777

rar is pending

**Comment by monsta** [comment]
Cool, I've picked the latest commit for 1.18 branch too.

**Comment by zhuyaliang** [comment]
@mirkander Please test if the issue still exists
