### ISSUE TITLE
[Wishlist] Add Zstd integration

### ISSUE THREAD

**Issue by dhdl** [mate-desktop/engrampa#186]
Much more relevant than ZPAQ would be a [Zstandard](https://en.wikipedia.org/wiki/Zstandard) integration.

Zstd uses Finite State Entropy and scales very good. It is faster faster & better compressing than zlib and at the same time much faster than xz (lzma) while delivering only a slightly worse compression ratio.

![benchmark](https://user-images.githubusercontent.com/31694945/30120240-932c18a6-9328-11e7-80b6-9dac564cc9ce.png)

For further benchmarks on your own hardware you may try [TurboBench](https://github.com/powturbo/TurboBench)

Sources are at https://github.com/facebook/zstd

**Comment by stokito** [comment]
Recently I added Brotli support and it seems that zstd is also not so hard to add. I'll try to add it soon.
