### ISSUE TITLE
engrampa 1.14.1 help documenation is missing

### ISSUE THREAD

**Issue by newlinnygirl** [mate-desktop/engrampa#187]
#### Expected behaviour
I choose"help" on the archive manager

#### Actual behaviour
I wanted to read written documentation on how to delete an archived file.  There is no help information to read.

#### Steps to reproduce the behaviour
I clicked on the roller icon.  Opened up the archive manager and clicked "Help"  

#### MATE general version
18.2

#### Package version
Engrampa 1.14.1

#### Linux Distribution
Mint

**Comment by raveit65** [comment]
1.14.x is obsolete and will never get updates from our side.
....... we are a small project.
Please bother your distro maintainers to update your distro.
