### ISSUE TITLE
Engrampa will not save rpm files

### ISSUE THREAD

**Issue by DavidParkin** [mate-desktop/engrampa#189]
Engrampa will open an archive but when asked to save it, as a file, bit for bit, it refuses, format unrecognised

**Comment by raveit65** [comment]
You can't edit rpms.
If you want to change an rpm you need to create it new from SPEC file.
'rpmbuild -ba spec-file.spec'

Not an issue!

**Comment by DavidParkin** [comment]
I don't wish to change them. I took the option to open the rpm, basically just a gzip archive, to see if it was what I wanted. It was, so I thought I would save it to use locally. However Engrampa refused to save it. That's right it knows enough to open the archive and display the contents perfectly. It just wouldn't let me save the whole blob. It is not normally required to understand the structure of a file to save it from memory to disk. I had to copy from my /tmp to home. It just surprised me.

**Comment by kn00tcn** [comment]
i'm not sure it's common for any software to raw copy a file upon save when there are no changes or if it's readonly, my first instinct would have been to manually copy from tmp (but then what if that's deleted while it's still in memory)

**Comment by lukefromdc** [comment]
No reason to open and save a read-only file like an RPM or a DEB from Engrampa when the same file can just be copied in caja, any other file manager, or for that matter with cp from terminal

**Comment by kn00tcn** [comment]
OP's reason (i think?) was that the file was buried in an unknown temp location (such as when clicking 'open' from a browser on a web page)

but as long as engrampa has the properties screen that lets you copy the path, it's ok enough

**Comment by DavidParkin** [comment]
Missed this but the reason as I recall was that it was a download which I chose to open instead of saving to disk immediately. Having seen that it was what I wanted, I tried to save it somewhere. Not a big problem, just surprised.
