### ISSUE TITLE
engrampa does'nt open odt files

### ISSUE THREAD

**Issue by jtm56** [mate-desktop/engrampa#193]
#### engrampa does'nt open those files (while trying to open, engrampa reports:...engrampa does not support odt-type of archives).

file-roller can open these files, because odt files are sort of zip-archives.

**Comment by flexiondotorg** [comment]
odt is a filw format from the Open Document Foundation used by software such as LibreOffice. Why should Engrampa be able to open such files?

**Comment by jtm56** [comment]
Yes, i know.
but odt is, as I said, a zip-format. You can open it (e.g. with file-roller[!]) and change the content, which could be sometimes necessary).
as engrampa is a fork of file-roller I expected it to have the same features

**Comment by jtm56** [comment]
Okay, seems that engrampa cannot.
Since engrampa is the default unzip program in mate I thought it should be able to do what most other unzip programs (including file-roller) can do.

**Comment by alexarnaud** [comment]
@flexiondotorg is there any easyHacks label for Mate ? 

Maybe it could just be a little trick to make ODT recognize as supported mime-type. But I haven't look more deeply because I'm busy on accessibility stuff.

Best regards.

**Comment by GM-Script-Writer-62850** [comment]
Here are some mime types:
```
application/vnd.oasis.opendocument.presentation
application/vnd.oasis.opendocument.presentation
application/vnd.oasis.opendocument.spreadsheet
application/vnd.oasis.opendocument.text
application/vnd.oasis.opendocument.presentation-template
application/vnd.oasis.opendocument.spreadsheet-template
application/vnd.oasis.opendocument.text-template
```
Here is the list of mime types for zip files in engrampa:
https://github.com/mate-desktop/engrampa/blob/master/src/fr-command-zip.c#L384-L389
Try adding them, compiling engrampa, and see if they work
