### ISSUE TITLE
Please install .appdata.xml file to correct metainfo location

### ISSUE THREAD

**Issue by sunweaver** [mate-desktop/engrampa#195]
In Debian, the .appdata.xml (apspstream) file goes into /usr/share/metainfo.

See here for the workaround, I currently have in debian/rules:
https://anonscm.debian.org/cgit/pkg-mate/engrampa.git/commit/?id=6156b307ed517c65a0f6cbcce0fc1a799ef7b15e

**Comment by monsta** [comment]
Fixed in https://github.com/mate-desktop/engrampa/commit/a699fa2db6fea3e9621800b00416bdf9b7b99728, picked to 1.20 branch in https://github.com/mate-desktop/engrampa/commit/b683362344ad14fd6ae87b628a90c9ec0180a76d.
