### ISSUE TITLE
usr_bin_engrampa.1000.crash 

### ISSUE THREAD

**Issue by balonballot** [mate-desktop/engrampa#196]
I wasn't sure what caused the crash but it was on the system reports.
https://gist.github.com/anonymous/d1d380806df4bdba26d324c19bb546ae

**Comment by sc0w** [comment]
I don't understand it

How to reproduce the crash step by step?

**Comment by zhuyaliang** [comment]
Please test if the issue still exists

**Comment by zhuyaliang** [comment]
#311 Fixed the issue
