### ISSUE TITLE
I would like to enter more rar options

### ISSUE THREAD

**Issue by ltspicer** [mate-desktop/engrampa#197]
I would like to enter more rar options like
rar a **-vn** -v100m **-m0** test.rar

How can I do that?
Or is it possible to add more input fields?

#### MATE general version
1.18.0

#### Package version
1.18.3

#### Linux Distribution
Linux Mint 18.3

**Comment by sc0w** [comment]
@treki1 can you explain it better?

what means **-vn** and **-m0** ?

**Comment by treki1** [comment]
vn                Use the old style volume naming scheme
m<0..5>       Set compression level (0-store...3-default...5-maximal)

**Comment by kn00tcn** [comment]
actually, for now you can make a `.rarrc` https://wiki.archlinux.org/index.php/RAR#Configuration_file

**Comment by zhuyaliang** [comment]
Please test if the issue still exists

**Comment by ltspicer** [comment]
How can I test this?
I always use the officially offered packages.
Currently Linux Mint 21.2 mate

**Comment by zhuyaliang** [comment]
@ltspicer This should be helpful to you
> actually, for now you can make a `.rarrc` https://wiki.archlinux.org/index.php/RAR#Configuration_file

**Comment by ltspicer** [comment]
Ah ok, I thought that was a new option in engrampa. Sorry
