### ISSUE TITLE
supporting GNU and BSD archive (.ar) format

### ISSUE THREAD

**Issue by darealshinji** [mate-desktop/engrampa#198]
#### Expected behaviour
Should open a GNU format .ar archive.

#### Actual behaviour
Engrampa says "Archive type not supported".
The README file on this repository also says that only AIX Small Indexed Archive is supported.
The file format seems to be not so complicated: https://en.wikipedia.org/wiki/Ar_(Unix)#File_format_details
I guess Engrampa could also use ar(1) to at least list the files.

#### Steps to reproduce the behaviour
Open a GNU format .ar archive (with Engrampa 1.12.0).

#### MATE general version
1.12.2

#### Package version
1.12.0-2

#### Linux Distribution
Ubuntu 16.04

#### Link to downstream report of your Distribution
None.

**Comment by sc0w** [comment]
**.ar** format is supported here in engrampa 1.20.0

https://github.com/mate-desktop/engrampa/blob/master/src/fr-command-ar.c

engrampa 1.12.0 is a very old version

you can report it to the maintainer of your linux distribution

**Comment by alexarnaud** [comment]
Le 22/03/2018 à 11:46, ZenWalker a écrit :
> engrampa 1.12.0 is a very old version
> 
> you can report it to the maintainer of your linux distribution

As an additional information: Ubuntu Mate 18.04 will be shipped with the 
support of the ar format.

Best regards,
Alex.

**Comment by darealshinji** [comment]
Great, thanks for the info. I don't know if a bug report for Ubuntu 16.04 would change anything, I think on Ubuntu they just backport bugfixes, not new features. But I will probably switch to 18.04 soon after its release.

**Comment by sc0w** [comment]
@darealshinji to make sure, can you attach here **.ar** files with that formats to test it?

**Comment by monsta** [comment]
> I don't know if a bug report for Ubuntu 16.04 would change anything, I think on Ubuntu they just backport bugfixes, not new features. 

You can use the official PPA to upgrade to 1.16:
https://ubuntu-mate.org/blog/mate-desktop-116-for-xenial-xerus/

By now it's an old version too, but at least it's something.

**Comment by sc0w** [comment]
btw, I can open **.ar** files with engrampa 1.8.1 (debian jessie vm)

**Comment by darealshinji** [comment]
Using engrampa 1.20.0 on Ubuntu 18.04 but I still cannot open ar files.
An example file I cannot open is attached:
[libfltk_forms.a.zip](https://github.com/mate-desktop/engrampa/files/2065912/libfltk_forms.a.zip)

**Comment by sc0w** [comment]
that file have extension **.a**

I renamed to **.ar** and engrampa can open it

**Comment by darealshinji** [comment]
Indeed, renaming it makes it open the file. However, .a is the default file extension here for archives, so shouldn't engrampa treat .a files as archives by default? Or maybe at least check the header and if it's '!<arch>' then open it.

**Comment by sc0w** [comment]
@darealshinji  Fixed in https://github.com/mate-desktop/engrampa/commit/499e600d758578eeb8187f92d0c12b36e50f7595

**Comment by darealshinji** [comment]
Thanks.
