### ISSUE TITLE
temp file is created in wrong directory

### ISSUE THREAD

**Issue by GM-Script-Writer-62850** [mate-desktop/engrampa#200]
#### Expected behaviour
when making a 7z or zip file the .tmp file should be stored in the output directory or in /tmp/
 * /tmp/ may be safer as it is possible the output dir is readonly, but the target file is read write
 * but it would be faster to write it to the output directory if /tmp is a separate storage space, so maybe /tmp can be used as a backup is permission is denied

#### Actual behaviour
when making a 7z or zip file the .tmp file should be stored in the input directory
this results in failure when the input directory is readonly

#### Steps to reproduce the behaviour
`ext='zip';archive="/home/$USER/Downloads/Adwaita.$ext";engrampa /usr/share/themes/Adwaita/* -a $archive;echo "engrampa exit status: $?";if [ -f $archive ];then rm $archive;echo "Success";else echo "Failure";fi`
change the ext value form zip to test other archive formats, i did not test them all but the only ones i have found to fail are zip and 7z

#### MATE general version
N/A

#### Package version
1.20.0-0ubuntu1

#### Linux Distribution
xubuntu 18.04 / ubuntu mate 18.04

#### Link to downstream report of your Distribution
https://bugs.launchpad.net/ubuntu/+source/engrampa/+bug/1764116
 * note attachment in comment 4

**Comment by stumper932** [comment]
Ubuntu-Mate 18.04LTS, engrampa 1.20.0-1 amd64

I had engrampa creating a tmp file on an sdcard instead of in the target directory, and this was "really" slow. So i had to do this via the terminal with zip.

cd /path/to/folder/
zip -rv --exclude=Somedir* /path/to/folder/backup_today.zip .

**Comment by lukefromdc** [comment]
I wonder what would cause Engrampa to look in a different filesystem entirely for a place to make the temp directory?

**Comment by stumper932** [comment]
To reproduce:
1. In "caja" navigated to sdcard and selected files.
2. Then chose "compress" from context-menu.
3. Engrampa opens, filled in the "filename.zip"
4. Switched "location" to "/home/user"
5. "filename.zip.tmp" is created in "source" folder instead of "target" folder.

**Comment by lukefromdc** [comment]
I just tried that on Debian Unstable with a USB flash drive, setting the desktop as the destination for the compressed file. This happened with a .gz or .7z file as the destination archive, but if the destination archive was a tar.gz the temporary folder appeared on the desktop.  This of course is only a problem when copying and compressing from a slow filesystem to a much faster one, and if going the other way (putting a compressed archive of something on an SSD  on a USB 2 flash drive for instance) might be the preferred behavior.  None the less, this is confirmed

**Comment by GM-Script-Writer-62850** [comment]
It is possible for the source directory to be read-only eg: /var/log
