### ISSUE TITLE
Wrong Date displayed in Engrampa

### ISSUE THREAD

**Issue by crazyBaboon** [mate-desktop/engrampa#205]
#### Expected behaviour

When I extract files to a folder, I expect them to have the date of the extraction. In my case the extraction is 23 of Jun and the extracted folders have the 11 Jun.

#### Steps to reproduce the behaviour

Just use Engrampa.

#### MATE general version

I am using Xubuntu 18.04, so no MATE here...

#### Package version

I am using Engrampa 1.20.0.

**Comment by kn00tcn** [comment]
i definitely do not want files to be altered without having an option for it (note: i dont know if there's a buried setting)
