### ISSUE TITLE
Cyrillic support

### ISSUE THREAD

**Issue by r3d9u11** [mate-desktop/engrampa#210]
#### Expected behaviour
correct file names into zip-archives maked in windows

#### Actual behaviour
![screenshot at 2018-07-18 09-53-48](https://user-images.githubusercontent.com/15020827/42864851-7ba57b60-8a70-11e8-8e12-e29fde160709.png)

#### Steps to reproduce the behaviour
any file names with a cyrillic symbols

#### MATE general version
any
#### Package version
any

#### Linux Distribution
any

Please, fix this veerryyy oold trouble with zip ( it is really pain :sob: )
(unar do it correctly, but I don't know how to use unar with engrampa)

Thanks.

**Comment by cranes-bill** [comment]
This is most likely a **7 zip** issue. I think it was fixed, but if it was, so it seems currently has a regression.
However, the following patch should work-around this issue, as well as #102, as probably #204
``` diff
 src/fr-command-7z.c | 12 +++++++++++-
 1 file changed, 11 insertions(+), 1 deletion(-)

diff --git a/src/fr-command-7z.c b/src/fr-command-7z.c
index a41f97d..0bbe082 100644
--- a/src/fr-command-7z.c
+++ b/src/fr-command-7z.c
@@ -247,12 +247,22 @@ list__begin (gpointer data)
 
 
 static void
-fr_command_7z_list (FrCommand  *comm)
+fr_command_7z_list (FrCommand  *comm, const char *mime_type)
 {
 	rar_check_multi_volume (comm);
 
 	fr_process_set_out_line_func (comm->process, list__process_line, comm);
 
+	if (is_mime_type (mime_type, "application/zip")) {
+	fr_process_begin_command (comm->process, "unzip");
+	fr_process_set_begin_func (comm->process, list__begin, comm);
+	fr_process_add_arg (comm->process, "-ZTs");
+	fr_process_add_arg (comm->process, "--");
+	fr_process_add_arg (comm->process, comm->filename);
+	fr_process_end_command (comm->process);
+	fr_process_start (comm->process);
+	}
+	else
 	fr_command_7z_begin_command (comm);
 	fr_process_set_begin_func (comm->process, list__begin, comm);
 	fr_process_add_arg (comm->process, "l");
```

**Comment by cranes-bill** [comment]
I used the file from #102 (last post), i also do not have other one to try with  ¯_(ツ)_/¯

**Comment by r3d9u11** [comment]
@cranes-bill yes, I have

**Comment by sc0w** [comment]
I did some tests, and `engrampa` with that file using `unar` works, the names are displayed correctly, but it is opened in "read only" mode

**Comment by r3d9u11** [comment]
@sc0w unar works corretly. But I can't find information, how to set unar as default "backend" for engrampa :( How to do it?

**Comment by sc0w** [comment]
@r3d9u11 with little changes in the code, but it is unacceptable by default, because we loss the ability to add files to `.zip`, seems `unar` only supports extract files

I will investigate to use a gsettings key to do the change

**Comment by sc0w** [comment]
https://github.com/mate-desktop/engrampa/pull/213 ready to test

**Comment by jackssirs** [comment]
the code you commit is not use
the version of the engrampa is: engrampa-1.16.1
i open terminal and start engrampa
the error code is:

(engrampa:1806): GLib-GIO-ERROR **: Settings schema 'org.mate.engrampa.general' does not contain a key named 'unar-open-zip'

and i unzip the chinese  zip file code random 。use the unar is good,but he interface is code random . can zip file the same to rar file

**Comment by sc0w** [comment]
@jackssirs I answered you here: https://github.com/mate-desktop/engrampa/pull/213#issuecomment-413507720

**Comment by viscropst** [comment]
openSUSE's solution is add a wrapper to unzip and its unitiles to solve the some filename what isn't encoding with UTF-8. So if it's use the unar we must add the arguments to set the encoding to uncompress the file to avoid the filename with some spific text encodings.
