### ISSUE TITLE
"Recently used toolbar" does not work

### ISSUE THREAD

**Issue by ghost** [mate-desktop/engrampa#211]
#### Expected behaviour
"Recently used" list to appears.

#### Actual behaviour
Button looks active, but "Recently used" list does not appear.
![capture du 2018-07-31 12 12 07](https://user-images.githubusercontent.com/5161278/43450409-53ae6fcc-94bb-11e8-85f5-b9184961e023.png)

**NOTE:** _This feature works as expected from the menu option._
#### Steps to reproduce the behaviour
Just click "Recently used toolbar" button.

#### Package version
7c0038a
(Also tried with 1.16.1 and it's the same)

**Comment by cranes-bill** [comment]
Well, i'm not developer, but i can't see a code related to this arrow in the source file, but there is a duplicated code for 'Open file' action instead   o_O

**Comment by lukefromdc** [comment]
Any chance you have set gtk-recent-files-max-age=0 in ~/.config/gtk-3.0/settings.ini ? That is how you deliberately disable history-saving when privacy is a concern. If you have that left over from a previous setup it would cause your problem.

**Comment by cranes-bill** [comment]
@lukefromdc Nope, i don't. Also as already noticed, it works from the menu option! For me, something's wrong, because the both buttons should not have same tooltip (and icon)...
Does this work to you!?

**Comment by vkareh** [comment]
I can confirm this issue as well. If you go to *Archive -> Open Recent", I get a list of recent files opened. However, clicking on the toolbar drop-down arrow next to the "Open" button nothing shows up.

**Comment by lukefromdc** [comment]
On resetting gtk-recent-files-max-age=1 for a test of Engrampa,  I found the button can be pressed but nothing pops up in response.
