### ISSUE TITLE
Adding pause and start functions

### ISSUE THREAD

**Issue by zhuyaliang** [mate-desktop/engrampa#234]
@raveit65 Do you need to add pause and startup functions? For example, when decompressing, click the button to pause decompression and click again to start decompression. I have finished this work, and I can provide patches if necessary.

**Comment by raveit65** [comment]
Maybe it is usefull for large disk images?
Let's call engrampa maintainer.
@sc0w  Thoughts?

**Comment by sc0w** [comment]
> I have finished this work, and I can provide patches if necessary.

Please, feel free to open new pull request and we can analyze it :)

**Comment by zhuyaliang** [comment]
@sc0w @raveit65  I made a new pull request.

**Comment by sc0w** [comment]
already implemented in https://github.com/mate-desktop/engrampa/pull/236 with https://github.com/mate-desktop/engrampa/commit/5eea3e1c074787c4082993e977af30644cec9775
