### ISSUE TITLE
unrar in engrampa ignoring an entire folder of files, but commandline unrar works fine

### ISSUE THREAD

**Issue by kn00tcn** [mate-desktop/engrampa#243]
this doesnt make sense, but i have found an archive that just skips over a specific folder & all files within it **only upon engrampa's extraction**, yet commandline unrar/rar works even though it's all the same version, the contents are basically:

> /file1
> /file2
> /folder1/file3
> /folder1/sub/filenameA
> /folder1/sub/filenameB
> /folder2/filenameA
> /folder2/filenameB

the two folders have the same filenames with a different size/date, everything is visible by name, but folder2 & each of its files are completely ignored when extracting in engrampa

(maybe i should say 'dir', seems more legible in the structure example, but less legible in the issue title)

i can open individual files from within engrampa, which puts them in /tmp/, but nothing shows up at the destination when pressing extract, this really makes no sense since it has to extract to open in the first place

engrampa's 'quit/show/close' doesnt appear either when extracting folder2 or its files, until i open a file then it finally pops up (even though there's nothing to show)

using `unrar` or `rar` commandline to extract has no problem, everything appears

i do not think there are non-ascii characters, i tried pasting from the rename dialog into an online non-ascii checker or with `grep -P -n '[^\x00-\x7f]'` which detect emoji, so it's probably not the name

is there a log or something? what command is engrampa doing?

(rar is not posted for reasons, i can PM)

**Comment by sc0w** [comment]
It is working fine here with engrampa 1.20.2

I have tested with this file (rar is inside the zip file):

[issue243.zip](https://github.com/mate-desktop/engrampa/files/2719298/issue243.zip)

**Comment by kn00tcn** [comment]
yes, of course it works fine when creating a new one

i can even extract from commandline, then create a new rar with all the same files, then there's no issue

so it's something specific to the one rar or the person that made it or some specific version of rar or winrar that created it

i've never seen this happen before until i noticed something was missing from my extracted files, now there's a concern that this may not be the first time

want me to email it?

**Comment by kn00tcn** [comment]
wait, i tried recreating all files now, originally my recreation didnt use the root ones, the issue has appeared again!

**Comment by sc0w** [comment]
I did the rar file exactly as you mentioned with the same names and different size/date and I can extract the files with no problems

**Comment by kn00tcn** [comment]
i have found the way to reproduce!

> /foldername/
> /foldername anotherword/

or

> /folder name/
> /folder name longer/

THAT is the issue, when a second folder starts with the same string, but then has a space & additional characters

**Comment by kn00tcn** [comment]
[engrampa-issue.zip](https://github.com/mate-desktop/engrampa/files/2719919/engrampa-issue.zip)

**Comment by sc0w** [comment]
that file works fine here, I can extract the same files I see in command line rar

**Comment by sc0w** [comment]
step by step what do you do? and what is the expected / actual behavior with that file?

**Comment by sc0w** [comment]
ok, I can reproduce the issue with this step:

> open rar in engrampa > select the two folders > extract (with overwrite files option DISabled) > only the first gets extracted, second is missing

with "overwrite existing files" enabled, it works fine, if it is disabled only extracts the first folder

btw, with **unar** (free software) it works fine

just install **unar** and uninstall **rar** / **unrar** :)

@mate-desktop/core-team for me, all the rar/unrar code can be removed, I hate non-free software :)

**Comment by lukefromdc** [comment]
Downside of Unar is it installs at least 15MB of Gnustep dependencies (at least on Debian). If something is closed source it should be avoided, but license term issues are basically a problem for distros. Ideally this would work with both to the extent the backends permit it.

There is also the unrar-free program that is compact and handles MOST (not all) of these sort of files. I have to limit the size of my filesystem to avoid unbounded growth of it, given I have to be able to make and manipulate backup images of it.

**Comment by kn00tcn** [comment]
unrar actually seems to have an open source option https://rarlab.com/rar_add.htm (only the format is proprietary or something like that)

it's possible that rpmfusion uses that source, i havent tried it yet, was using the official binary when i noticed the issue

what's/where's "unrar-free"?

**Comment by lukefromdc** [comment]
Unrar-free is the name of a Debian package
https://packages.debian.org/sid/unrar-free

I checked your provided link for rarlabs and REALLY did not like their business model for the full package, which is based on selling paid software to Windows users. About as non-GPL compatable as it gets, thus unrar is in the "non-free" section of Debian for unacceptable licensing terms and not just some software patent:

"Section 6 The "Try Before You Buy" Model

The Customer may download the RAR Software, at no charge, from the Web sites www.win-rar.com and www.rarlab.com and use the software, again at no charge, for 40 days. During this period, all of the functions of the RAR Software are available to the user with the exception of the functions: "Add authenticity information", "Show protocol file" and "Delete protocol file". The purchaser should test the RAR Software during this test phase to determine if it meets his requirements and needs. In particular, the Customer must determine if the RAR Software runs under his operating system and in his desired hardware and software environment. He promises to acquire a Licence for the RAR Software only if and when he has assured himself that he can answer the above-mentioned questions with "yes".

Section 7 Conclusion of the Purchase Contract

A click on the link "Order" will take the user to the online shop. This online shop is operated on behalf of win.rar GmbH by Element 5 AG within the framework of the ShareIt! registration service. By clicking on the link "Customer Service" on the online shop site, the Customer can retrieve information about the procedure for placing an order. The Customer makes a binding offer for the conclusion of a purchase contract between the Customer and win.rar GmbH by clicking on the "Order" button.
Win.rar GmbH accepts the offer by sending the Licence key to the Customer by e-mail. "

**Comment by kn00tcn** [comment]
on windows, nothing is disabled, it just pops up a single message with a close button (no timer) upon winrar startup, it might not even popup anything if all you use is the file manager context menus to create/extract

(the authenticity feature you quoted sounds like maybe a cert, only relevant for enterprise)

i will test later, also curious if this might show up in other formats since it's tied to the 'overwrite' option

is there a list of engrampa's supported formats that are auto-detected based on the libs/bins installed on the system?

**Comment by lukefromdc** [comment]
engrampa --help and man engrampa don't show any such list, but they would not as they are based on code shipped with the program.  I would imagine that the list of options displayed when you select "compress" for a single file in Caja would be that list but I do not know for sure if they are checked before populating that menu.

**Comment by sc0w** [comment]
**unrar-free** project is dead, it isn't a real alternative, we can see in the debian package description:

> Can't handle some archives in the RAR 3.0 format natively. Package "unar" can be used to extract those archives if installed. 

@kn00tcn you have tested engrampa with **unar** installed ?

**Comment by sc0w** [comment]
in debian we have the package **p7zip-rar** but it is non free
