### ISSUE TITLE
Application state not saved and restored in session save/new session

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/engrampa#245]
#### Expected behaviour
If saving sessions is enabled  ( org>mate>desktop>session>auto-save-session set to TRUE), than an open engrampa window should reappear on logging out and back in.

#### Actual behaviour
Engrampa windows do not reappear on starting a new session after logging out with an engrampa window open and session saving enabled

#### Steps to reproduce the behaviour
Set  org>mate>desktop>session>auto-save-session to TRUE
Open an archive in engrampa
log out
log back in
Engrampa window does not reappear

Note that in main.c session saving and restoration supported by the functions
`fr_restore_session `
and
`fr_save_state`
my guess is when engrampa was ported from libunique to GtkApplication this got broken. No problem making that work, it works fine in Caja.

#### MATE general version
1.21

#### Package version
engrampa 1.21.0 from git master current as of Jan 5 2019, locally compiled

#### Linux Distribution
Debian Unstable with locally built gtk 3.24.3 and glib 2.59.0

#### Link to downstream report of your Distribution
None as this is a local build

**Comment by zhuyaliang** [comment]
@lukefromdc I have fixed this issue, please test it
