### ISSUE TITLE
Support Debian udeb packages

### ISSUE THREAD

**Issue by johnraff** [mate-desktop/engrampa#246]
#### Expected behaviour
Using engrampa to open file with ending .udeb should display contents, as with .deb file.

#### Actual behaviour
Fails to open archive, with message: "Archive type not supported".
If archive is renamed with .deb ending, then contents are displayed normally. (udeb and deb are essentially the same file type.)

#### Steps to reproduce the behaviour
As above.

#### MATE general version
N/A 

#### Package version
1.20.2

#### Linux Distribution
Debian Stretch 9.7

#### Link to downstream report of your Distribution
(none)

Since the two file types (.deb and .udeb) are essentially the same, maybe something similar to the recent fix for handling .a files as .ar would be sufficient for this? https://github.com/mate-desktop/engrampa/commit/499e600d758578eeb8187f92d0c12b36e50f7595

**Comment by rubyFeedback** [comment]
Are they really the same? If so perhaps it is just a simple check against .deb that cuold be extended towards .udeb.

**Comment by johnraff** [comment]
I'm pretty sure the compression method is the same. (The difference is in the contents - udebs are minimal versions of debs, without docs etc.) I have renamed .udeb files to .deb and then engrampa successfully opens them.
