### ISSUE TITLE
[Feature request, commandline] Would it be possible to enable:  "engrampa --version"?

### ISSUE THREAD

**Issue by rubyFeedback** [mate-desktop/engrampa#255]
Would it be possible to enable:  "engrampa --version"?

I would like to have this functionality so that I can, on the commandline,
show which mate-desktop components are available, for which version.

It is possible to work around this e. g. by looking at the version string
in .so, but it would be more elegant and consistent IMO if --version
would be supported by engrampa. Please feel free to close this
issue request at any moment in time.

**Comment by vkareh** [comment]
This was just fixed 2 days ago :)

https://github.com/mate-desktop/engrampa/pull/253
