### ISSUE TITLE
egg_tree_multi_drag_button_release_event: Process /usr/bin/engrampa was killed by signal 11 (SIGSEGV)

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/engrampa#27]
Orginal report at fedora bugzilla.
https://bugzilla.redhat.com/show_bug.cgi?id=928984

 Mike Zet 2013-03-28 18:47:11 EDT

Description of problem:
Opening rar archive by MATE Caja File Manager

Version-Release number of selected component:
mate-file-archiver-1.5.1-6.fc18

Additional info:
backtrace_rating: 4
cmdline:        engrampa /home/michuzet/Pobrane/B0n1v3rF0r3mm4F0r3v3r4g0.rar
crash_function: egg_tree_multi_drag_button_release_event
executable:     /usr/bin/engrampa
kernel:         3.8.4-202.fc18.x86_64
uid:            1000
ureports_counter: 1

```
Truncated backtrace:
Thread no. 1 (7 frames)
 #0 egg_tree_multi_drag_button_release_event at eggtreemultidnd.c:204
 #1 _gtk_marshal_BOOLEAN__BOXED at gtkmarshalers.c:86
 #6 gtk_widget_event_internal at gtkwidget.c:5017
 #7 gtk_widget_event at gtkwidget.c:4814
 #8 gtk_propagate_event at gtkmain.c:2490
 #9 gtk_main_do_event at gtkmain.c:1685
 #15 gtk_main at gtkmain.c:1257
```

backtrace:
https://bugzilla.redhat.com/attachment.cgi?id=717876
core_backtrace:
https://bugzilla.redhat.com/attachment.cgi?id=717878

 glad08 2013-04-24 08:55:50 EDT

I try to open zip archive by double clicking from caja.

backtrace_rating: 4
cmdline:        engrampa /home/titov/svn/development/gui/js/gwt/images.zip
crash_function: egg_tree_multi_drag_button_release_event
executable:     /usr/bin/engrampa
kernel:         3.8.8-202.fc18.x86_64
package:        mate-file-archiver-1.5.1-6.fc18
reason:         Process /usr/bin/engrampa was killed by signal 11 (SIGSEGV)
uid:            1000
ureports_counter: 1

 glad08 2013-07-16 10:03:20 EDT

I get this bug again when open archive which attached above and double click inside it on QR folder, after that engrampa crashes.

I could upload detailed info about crash from gnome-abrt history if somebody say me how (which files needed and where find it in my system).

backtrace glad08:
https://bugzilla.redhat.com/attachment.cgi?id=774649

 glad08 2013-07-17 03:18:21 EDT

No, I use mate-file-archiver-1.6.0-2.fc18.x86_64 from fedora 18 repo. Is it not latest version? Should I install mate-file-archiver from testing repo?

I can open that archive both from mate-file-archiver and from caja by doubleclicking. I observe crash just one time - the first time, and not at the moment of doubleclicking on file, but at the moment I double click on folder inside archive when archive was already opened in mate-file-archiver.
The next attempts are all be successfull - program doesn't crash anymore. I don't know what it may be. Can only suggest it may be related to some action, which doing just once for each archive - some caching, generating previews or any such things like that.

Backtrace I attached above.

**Comment by hussamT** [comment]
If your hand shakes a bit while traversing folders in an archive, you will see the crash. It's not very easy to reproduce this.
