### ISSUE TITLE
Filename encoding in zip archives is processed incorrectly

### ISSUE THREAD

**Issue by unxed** [mate-desktop/engrampa#278]
#### Expected behaviour
Listing files in .zip as unzip does:
![Снимок экрана в 2019-07-01 09-55-54](https://user-images.githubusercontent.com/1151423/60416440-8228b500-9be6-11e9-86da-c2fb6a357e26.png)

#### Actual behaviour
![Снимок экрана в 2019-07-01 09-56-58](https://user-images.githubusercontent.com/1151423/60416493-9f5d8380-9be6-11e9-84af-878a29d5a8df.png)

#### Steps to reproduce the behaviour
1. Open attached .zip file in engrampa
[Desktop.zip](https://github.com/mate-desktop/engrampa/files/3344256/Desktop.zip)

#### MATE general version
1.20.1

#### Package version
mate-desktop-environment (2018.11.28 linuxmint:19.1/tessa [all])

#### Linux Distribution
Linux Mint 19.1 amd64

#### Link to downstream report of your Distribution
n/a

Corresponding p7zip issue looks abandoned.
https://sourceforge.net/p/p7zip/bugs/187/

Can we just use unzip instead?

**Comment by sc0w** [comment]
You can use `unar` instead, since the commit https://github.com/mate-desktop/engrampa/commit/c587ae127cf0d6fee6b7e8c21bbe1c903faac13c

![2019-07-09_02-20](https://user-images.githubusercontent.com/7734191/60850609-5f9f2900-a1f0-11e9-8d77-2930b58583d4.png)

**Comment by unxed** [comment]
FYN: charset issue is fixed in Debian's 7-zip package:
https://salsa.debian.org/debian/7zip/-/merge_requests/8

and also in my unzip fork:
https://github.com/unxed/unzip/

**Comment by unxed** [comment]
Corresponding unzip fix merged to Ubuntu
https://git.launchpad.net/ubuntu/+source/unzip/commit/?id=8d0362fcc3761dc75fe42de312eb5a067533f68d
