### ISSUE TITLE
Engrampa ignores leading whitespace of (at least) directories.

### ISSUE THREAD

**Issue by RobertZenz** [mate-desktop/engrampa#299]
Follow-up from #291.

Engrampa ignores leading whitespace of (at least) directories.

 1. Create two directories "test" and " test" `mkdir "test" " test"`
 2. Pack them up `tar -cf test.tar "test" " test"`

If we view it with `tar` we get this:

```
$ tar -tf test.tar 
test/
 test/
```

However, Engrampa does only show one "test" directory in the archive.

Most curiously, this does not occur when you package them up as zip (which is part of the original bug report, as jars are only zip files).

**Comment by RobertZenz** [comment]
@rbuj A heads up, I've only tested it with tars, but I've also seen the same in a jar but could not reproduce it with a zip. So the other implementations should also be checked whether they have this problem.

**Comment by rbuj** [comment]
@RobertZenz  jar: blank spaces are not allowed in fully-qualified names.
