### ISSUE TITLE
Error parsing unace output

### ISSUE THREAD

**Issue by Miralasa** [mate-desktop/engrampa#303]
#### Expected behaviour
Engrampa lists contents of ACE archives.

#### Actual behaviour
Engrampa shows an extra item in the list, failing to detect its end.

#### Package version
1.22.1

Unace 2.5 uses an empty line between the file listing and the summary line when listing an archive. The reading of the listing should stop when empty line is encountered.

**Comment by sc0w** [comment]
> Engrampa shows an extra item in the list, failing to detect its end.

please, can you attach sample `.ace` file, and screenshots ?
