### ISSUE TITLE
BUG: Invalid msgstrings in it.po

### ISSUE THREAD

**Issue by gm10** [mate-desktop/engrampa#342]
There's two bad translations in it.po, causing the build to fail. Specifically:
```
/tmp/mate-build/engrampa/help $ msgfmt -o "it/it.mo" "it/it.po"
/tmp/mate-build/engrampa/help $ itstool -m it/it.mo C/index.docbook
Warning: Could not merge it translation for msgid:
To rename a file in an archive, perform the following steps:
Warning: Could not merge it translation for msgid:
You can use the file manager to extract files from an archive, in the following ways: <_:itemizedlist-1/>

```
I both cases the culprit is an `<_:orderedlist-1/>` entry when there should be none (first msgid) or `<_:itemizedlist-1/>` (second msgid).

**Comment by raveit65** [comment]
already fixed https://github.com/mate-desktop/engrampa/commit/3d9c77a403d7f6e531719a8aeadd67b7776727cd

**Comment by gm10** [comment]
@raveit65 nope, that commit is unrelated. Also my report was about the tip of master.

**Comment by raveit65** [comment]
@gm10 
Nope, i can build engrampa master after that fix.
```
- "Puoi aggiungere file ad un archivio nei seguenti modi: <_:orderedlist-1/>"
+ "Puoi aggiungere file ad un archivio nei seguenti modi: <_:itemizedlist-1/>"
```

PS: you forgot to post a line number of it/it.po wher build failed.

**Comment by raveit65** [comment]
re-open

**Comment by gm10** [comment]
Whether the build succeeds depends on the `ifstool` version, 2.0.5-2 just puts out the warning in the OP, previous versions crash. Either way, it's still a bug in the translations. I gave the msgids, but here are the lines:
https://github.com/mate-desktop/engrampa/blob/2b34062d1c53570831307b9a2882fff08c97a655/help/it/it.po#L1877
https://github.com/mate-desktop/engrampa/blob/2b34062d1c53570831307b9a2882fff08c97a655/help/it/it.po#L3065

**Comment by monsta** [comment]
Fixed on Transifex and pulled in https://github.com/mate-desktop/engrampa/commit/f0805f3afe61c035cc3477cba880322c15e95766.
