### ISSUE TITLE
full disk makes engrampa fail with meaningless error message

### ISSUE THREAD

**Issue by sezanzeb** [mate-desktop/engrampa#344]
#### Expected behaviour

Engrampa to say, or at least log to the console, that the disk is full. Or print a stack trace. anything.

#### Actual behaviour

There doesn't seem to be any log output at all for errors, it just says "an error occured" or something. no stack trace. nothing. The console remains completely empty

#### Steps to reproduce the behaviour

create an archive on a full disk

#### MATE general version

I'm running xfce, not mate

#### Package version

1.22.2-1

#### Linux Distribution

manjaro

#### Link to downstream report of your Distribution

what is this

**Comment by Majester** [comment]
Confitrmed on Ubuntu Mate 18.04
