### ISSUE TITLE
Can't open .ARC files and .PAK files with CAJA/engrampa

### ISSUE THREAD

**Issue by InfoLibre** [mate-desktop/engrampa#347]
#### Expected behaviour

Extracting files from .ARC and .PAK archives.

#### Actual behaviour

I can't extract files.

#### Steps to reproduce the behaviour

In CAJA, right-click on the .ARC or .PAK files. The menu **Extract here** is missing.

[MM34.PAK.zip](https://github.com/mate-desktop/engrampa/files/4010932/MM34.PAK.zip)

[EGACHESS.ARC.zip](https://github.com/mate-desktop/engrampa/files/4010937/EGACHESS.ARC.zip)

#### MATE general version

1.22.2

#### Package version

1.22.2

#### Linux Distribution

Linux Mint MATE 19.3

**Comment by Petrouchka** [comment]
I can extract files from .ARC archive with Midnight Commander.

**Comment by Petrouchka** [comment]
I can extract files from .PAK archive with unrar package. Can unrar be used by CAJA ?

**Comment by raveit65** [comment]
Can you please file out a report against your distro at linuxmint bugreporting system and ask there for help, or use Linuxmint forum.
Github is a developing and bugeporting tool, but not user support help line.
Thank you.

**Comment by Petrouchka** [comment]
@raveit65 If CAJA can't open .PAK and .ARC files, it's not a problem with how I use it but it's a bug. Dependencies between CAJA/engrampa and other softwares that can open .PAK and .ARC are missing. If you don't know how to solve this bug in CAJA, why are you closing it without any explanation ?
I take time to report it and your answer is contemptuous.

**Comment by raveit65** [comment]
> #### Link to downstream report of your Distribution

It is very contemptuous and respect-less that you don't honour our template and open a bugreport against your distro.
Anyway, re-opened and ignored by me.

**Comment by Petrouchka** [comment]
A opened a bugreport in my distro : https://github.com/linuxmint/linuxmint/issues/188 but they closed it too. Anyway, thank you rbuj for your help.
With my old ARC files, unar had a bug too. I wrote to macpax.com and they solved it and released a new version https://github.com/MacPaw/XADMaster/releases/tag/v1.10.7

**Comment by zhuyaliang** [comment]
So can we close this issue
