### ISSUE TITLE
Engrampa doesn't support zstd compressed .rpms

### ISSUE THREAD

**Issue by wally-mageia** [mate-desktop/engrampa#350]
Fedora ([Switch RPMs to zstd compression](https://fedoraproject.org/wiki/Changes/Switch_RPMs_to_zstd_compression)) and now also Mageia has switched to zstd compression for binary .rpms. Latest Engrampa 1.23.2 or git master doesn't support zstd compressed .rpms whereas for example file-roller supports them through libarchive.

> $ engrampa --version
> Engrampa Archive Manager 1.23.2

> $ rpm -qp --qf "%{NAME}-%{VERSION}-%{RELEASE}: %{PAYLOADCOMPRESSOR} %{PAYLOADFLAGS}\n" ./engrampa-1.23.2-1.mag8.x86_64.rpm
> engrampa-1.23.2-1.mag8: zstd 19

![screenshot](https://user-images.githubusercontent.com/5312085/71642756-043e8700-2cb9-11ea-8e24-b3b0d4edd37f.png)

**Comment by wally-mageia** [comment]
Indeed #351 fixes the issue. It would be nice to have this fixed also in 1.22 stable branch.

**Comment by raveit65** [comment]
>  It would be nice to have this fixed also in 1.22 stable branch.

Done.
https://github.com/mate-desktop/engrampa/commit/a37afa3068da849e8a5725101ae9bdf542591c46
