### ISSUE TITLE
bsdtar as an Arch replacement for cpio in 1.22.3

### ISSUE THREAD

**Issue by Cesura** [mate-desktop/engrampa#352]
Hi all,

I am the maintainer of engrampa (and all of MATE for that matter) for Arch Linux. In the past, we have built the package using a patch similar to [this one](https://github.com/mate-desktop-legacy-archive/archlinux-packages/blob/master/engrampa-gtk3/fr-rpm-bsdtar.patch).

However, I noticed that the directory structure has changed recently, as well as the underlying binaries that are invoked. I'm totally fine remaking the patch for the new version of course, but given the source changes I'd like to inquire 1) if this is still a relevant problem for non-RPM-based distros (I assume this is the case), and 2) if a similar change to the aforementioned patch will have any unintended consequences elsewhere in this version of engrampa.

Thanks!

**Comment by raveit65** [comment]
Sorry, we didn't kow that you patched out the rpm2cpio command for archlinux.
https://github.com/mate-desktop/engrampa/commit/4deb89e7fa95e8abffb86f517878a9bc0d30b7bc was needed to fix https://github.com/mate-desktop/engrampa/issues/350 for actual 1.22 branch for fedora and Mageia. Those distros and OpenSuse can use rpm2cpio binary from rpm package.
So, 1) isn't a problem.

**Comment by sc0w** [comment]
The patches along the time someday never works, it is better to make new pull request

**Comment by rbuj** [comment]
As far i know, we no longer need to expand the archive for listing the content. This speeds up the loading of large rpm files, such as the kernel rpm.
```shell
rpm -qp --nosignature --queryformat "[%10{FILEMODES:perms} %10{FILESIZES} %10{FILEMTIMES} %{FILENAMES} %{FILELINKTOS}\n]" RPMFILE
```

**Comment by Cesura** [comment]
@zhuyaliang I am no longer the MATE maintainer for Arch, but based on what I see in their current [PKGBUILD](https://gitlab.archlinux.org/archlinux/packaging/packages/engrampa/-/blob/main/PKGBUILD) , this issue is probably not relevant and can be closed.
