### ISSUE TITLE
Bulk Extraction Failing (Right Click)

### ISSUE THREAD

**Issue by g0tmi1k** [mate-desktop/engrampa#371]
- OS: Kali Linux 2020.1 (x64)
- Engrampa: v1.24.0-2 [Debian Package]
- Xfce v4.14 [Debian Package]
- Thunar v1.8.12 [Debian Package]
- thunar-archive-plugin v0.4.0-2 [Debian Package]

- - -

So the issue is, upon selection two or more files to extract I can't extract them both. It will only do the first one, and stop.

Will generate some random tar.gz files

```
kali@kali:~/Downloads$ ls
kali@kali:~/Downloads$
kali@kali:~/Downloads$ for x in $( seq 1 3 ); do
>   dd if=/dev/urandom of=file${x}.bin bs=1M count=1
>   tar -zvcf file${x}.tar.gz file${x}.bin
>   rm -f file${x}.bin
> done
1+0 records in
1+0 records out
1048576 bytes (1.0 MB, 1.0 MiB) copied, 0.0198063 s, 52.9 MB/s
file1.bin
1+0 records in
1+0 records out
1048576 bytes (1.0 MB, 1.0 MiB) copied, 0.0192154 s, 54.6 MB/s
file2.bin
1+0 records in
1+0 records out
1048576 bytes (1.0 MB, 1.0 MiB) copied, 0.0194023 s, 54.0 MB/s
file3.bin
kali@kali:~/Downloads$
kali@kali:~/Downloads$ file *
file1.tar.gz: gzip compressed data, from Unix, original size modulo 2^32 1054720
file2.tar.gz: gzip compressed data, from Unix, original size modulo 2^32 1054720
file3.tar.gz: gzip compressed data, from Unix, original size modulo 2^32 1054720
kali@kali:~/Downloads$
```
Now select them all, right click and then...

- selecting "Extract here" works as expected, all three extract as expected
- But doing "Extract To" just does the first one.

![](https://i.imgur.com/eYDat7T.gif)

**Comment by lukefromdc** [comment]
Confirmed here on Debian Unstable

**Comment by Majester** [comment]
Confirmed on Ubuntu Mate 18.04

**Comment by zhuyaliang** [comment]
Please try the latest version

**Comment by zhuyaliang** [comment]
@lukefromdc Please test again, this issue cannot be reproduced in the latest version

**Comment by lukefromdc** [comment]
On the road now, that has to wait until I get home

**Comment by lukefromdc** [comment]
Indeed, with current git master if I select two files to extract I get them both

**Comment by lukefromdc** [comment]
Before we close this it would be good to know what made the difference, so the fix could be cherrypicked to 1.26. I have a feeling it will be awhile before 1.28 is released

**Comment by lukefromdc** [comment]
I have never seen the extract to option so I don't know how to test this.

**Comment by zhuyaliang** [comment]
> I have never seen the extract to option so I don't know how to test this.

[05-13-2023Screen video05^%41^%24 PM.webm](https://github.com/mate-desktop/engrampa/assets/36913152/5cba2853-4622-485f-84ec-818b78322107)

**Comment by lukefromdc** [comment]
"extract-to" is in caja-engrampa. Issue and fix confirmed, fix merged
