### ISSUE TITLE
Cannot open RAR archives with encrypted file list

### ISSUE THREAD

**Issue by AngryPhantom** [mate-desktop/engrampa#374]
#### Actual behaviour
Encrypted RAR archives cannot be opened via Engrampa (as well as Gnome file-roller)

#### Steps to reproduce the behaviour
1. Install Debian Stable with MATE
2. Install the latest RAR for Linux version [5.90](https://www.rarlab.com/rar/rarlinux-5.9.0.tar.gz)

#### MATE general version
1.20.3

#### Linux Distribution
Debian Stable (32 & 64 bit)

Hello,
When I create an archive within Engrampa (or file-roller) and enable [Encrypt the file list](http://0x0.st/iMMd.png) option I can not open it afterwards and get the following [error](http://0x0.st/iMMn.png).

Everything was fine in versions before 5.80 (so I reverted back to using [5.7.1](https://www.rarlab.com/rar/rarlinux-5.7.1.tar.gz)). That's how [it should look](http://0x0.st/iMM7.png) when you open an archive.

I also started Engrampa from the console to see if there are any errors, but there weren't.

When I extract such archives **in console everything is OK**, so I guess it's not a RAR bug.
I also see there was a [similar problem](https://github.com/mate-desktop/engrampa/issues/3) here long ago.

Archives **created in Windows** and then being opened in Linux **are also OK** and it's really strange.

I contacted the developer ([Eugene Roshal](mailto:dev@rarlab.com)) and he said he needed some more information like what parameters are being passed from/to Engrampa or some other GTK library responsible for that in order to track this issue down.

Could you please provide such info? Probably we should open an issue somewhere in GNOME/GTK bug tracker...

Thank you in advance,
Alex

**Comment by txtsd** [comment]
This is happening to me in `engrampa 1.24.1`

1. Create a file with `rar u -hp test.rar`
2. Open test.rar in `engrampa`
3. Fails with the Incorrect Password modal

It lists the files in the archive fine in terminal with `rar l test.rar` though

**Comment by AngryPhantom** [comment]
I've tested this with Engrampa and Xarchiver some time ago and it fails to unpack such encrypted archives. I've contacted the author of RAR again and still didn't get any adequate answer. He thinks that the issue is in these GUI archive managers and not in his code.
So, I'm really not sure whether we have to keep this issue open. Should we simply bury this proprietary piece of... software and better stick to open-source? Should I close this?

**Comment by txtsd** [comment]
No, leave it open. It's definitely a bug in engrampa since rar and 7z are able to list and extract the archive correctly from the terminal.

**Comment by raveit65** [comment]
Anyone like to test linked PR?

**Comment by AngryPhantom** [comment]
@raveit65 I would really like to test this out. Actually I'm using Void Linux and XFCE but I guess I would be able to compile it there. Where can I get the fixed snapshot of it?

**Comment by raveit65** [comment]
Still wondering than you use the technical term `snapshot` but you don't know to compile linux software.
Sorry, we don't support this.
Please file out a report against your distribution and ask your distro maintainer to create a snapshot for you.

**Comment by raveit65** [comment]
```
git clone https://github.com/mate-desktop/engrampa.git
cd engrampa
git submodule init && git submodule update --remote --recursive
./autogen.sh
make
sudo make install
```
After you have installed all  needed -devel packages you will find a installation of engrampa in /usr/local/
Good luck...

**Comment by AngryPhantom** [comment]
@raveit65 I'm not a programmer/developer/coder, unfortunately, and I have a very little experience of compiling software. In Void Linux it's all a matter of xbps-src and a template (similar to PKGBUILD in Arch Linux), but it supports git releases only. Will be waiting for the next release of Engrampa.
Cheers and thanks for the fix!
