### ISSUE TITLE
File manager extension to integrate with Nemo

### ISSUE THREAD

**Issue by philipzae** [mate-desktop/engrampa#385]
Would be good if there was a Nemo extension to integrate with Engrampa.

https://github.com/linuxmint/nemo-extensions/issues/356

**Comment by zhuyaliang** [comment]
We have our own file manager [caja](https://github.com/mate-desktop/caja)
This should be what you need [nemo-extensions](https://github.com/fossfreedom/nemo-extensions/commit/ee1fb4883af3d04f39f221139c9779d4c7b75f12)
