### ISSUE TITLE
Ability to have toolbar use symbolic icons

### ISSUE THREAD

**Issue by philipzae** [mate-desktop/engrampa#387]
#### Expected behaviour
Toolbar icons to look similar to Thunar

#### Actual behaviour
Icons are different

#### Steps to reproduce the behaviour
1. Open Engrampa in Xubuntu 20.04
2. Open Thunar
3. Compare the navigation toolbar in each

#### Package version
1.24.0

#### Linux Distribution
Xubuntu 20.04

#### Link to downstream report of your Distribution
https://bugs.launchpad.net/ubuntu/+source/xubuntu-artwork/+bug/1872064

![preview](https://bugs.launchpad.net/ubuntu/+source/xubuntu-artwork/+bug/1872064/+attachment/5351312/+files/archive%20manager%20toolbar%20icons%202.png)

**Comment by zhuyaliang** [comment]
Why should the icon be the same as thunar?

**Comment by lukefromdc** [comment]
Icons come from your icon theme, though different file managers might call differently named icons. Caja shares code with Nemo and Nautilus but not with Thunar, I don't see us worrying about this
