### ISSUE TITLE
Suggestion: Remove final dialogbox

### ISSUE THREAD

**Issue by liar666** [mate-desktop/engrampa#388]
#### Expected behaviour
No dialogbox displayed. Eventually change the (color of) some GUI element to indicate that decompression is terminated OK/Not OK, but do not create a new window/dialog.

#### Actual behaviour
At the end of any decompression, a dialogbox is shown, displaying "Extraction completed successfully" asking if the user wants to Quit/Show the files/Show the files and Quit/Close.
The opening of this dialogbox is quite annoying, particularly when decompression takes time, and you switch to another task in the meantime, and then the "termination" pops up and takes the focus.

#### Steps to reproduce the behaviour
- Run 
  $ engrampa <archive>
- Select files/dirs inside de archive
- Click "Extract" button
- Select a destination dir
- Hit "Extract" button

#### MATE general version
Engrampa Archive Manager 1.24.0

#### Package version
Engrampa Archive Manager 1.24.0

#### Linux Distribution
XUbuntu 20.04

**Comment by dancer69** [comment]
I'm using engrampa because of this future mostly, which I found very useful in some situations. So, I disagree. I'd like this future to stay. It could be added a configuration option to enable/disable the dialogbox though.
