### ISSUE TITLE
Cannot save updated file within tar.gz/tar.xz archive, no response to "update" button, "Cancel" button work

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/engrampa#390]
#### Expected behaviour

On opening a tar.gz or tar.xz archive and modifying contained text file with Pluma, can save the modified file back to the archive. Clicking the "update" button triggers a save of the file back to the archive via its temporary directory

#### Actual behaviour
The "Update" button gets no response whatsover, the "cancel" button works. If running from terminal, this warning appears:
```
(engrampa:261787): Gtk-WARNING **: 01:48:01.852: Could not find signal handler 'on_update_files_ok_button_clicked'.  Did you compile with -rdynamic?

(engrampa:261787): Gtk-WARNING **: 01:48:01.852: Could not find signal handler 'on_update_file_ok_button_clicked'.  Did you compile with -rdynamic?
```
#### Steps to reproduce the behaviour
Install engrampa from current git master.
Open a tar.gz, tar.xz, or other updatable archive containing a text file in engrampa, open the text file, modify it, try to save the results. Nothing happens
NOTE THAT VERSIONS PRIOR TO MAY 12 2020 worked as expected. My next build was on 6-12-2020, so the problem came in between these dates. The new commits since May 12 and prior to June 12 are these:

commit 182db38e83a67d52e15888e3281c3b4dfc2bee40
Author: Wu Xiaotian <yetist@gmail.com>
Date:   Wed Apr 29 14:15:38 2020 +0800

    use git submodule of libegg

commit 3b36ed380545abf321922499c7969d69bae6e8cc
Author: rbuj <robert.buj@gmail.com>
Date:   Tue Apr 14 14:49:06 2020 +0200

    Require gtk+ 3.22 in glade files

commit af12d512815a111e64b172362331e7d34b4e18cf
Author: rbuj <robert.buj@gmail.com>
Date:   Tue Apr 14 13:33:49 2020 +0200

    dlg-batch-add: Set labels GtkSizeGroup in ui file

commit 4a0d9903b8f6b33b73b2e2bc578c9a237c67b4b3
Author: rbuj <robert.buj@gmail.com>
Date:   Tue Apr 14 13:21:22 2020 +0200

    Use callback symbols defined in ui files

commit c60e1cfb6c4296bcc9c4f05da3484f22e7f15770
Author: rbuj <robert.buj@gmail.com>
Date:   Thu Apr 2 15:59:02 2020 +0200

    gtk-utils: Remove _gtk_builder_get_widget

#### MATE general version
1.24

#### Package version
local build from git master as of 6-12-2020

#### Linux Distribution
Debian Unstable

#### Link to downstream report of your Distribution
None as this is a local build

**Comment by raveit65** [comment]
`git biscet` shouls show you the cluprit commit?

**Comment by rbuj** [comment]
culprit: commit 4a0d9903b8f6b33b73b2e2bc578c9a237c67b4b3

**Comment by lukefromdc** [comment]
I too can confirm the fix works, we are done with this one

**Comment by lukefromdc** [comment]
This problem or a similar one are now back, though this time the "cancel" button works while the "update" button has again stopped working. No messages related to this in terminal when running engrampa from there.,

**Comment by rbuj** [comment]
culprit: commit https://github.com/mate-desktop/engrampa/commit/d75c80047df558a76c7d276adbedf24e337f1650#
