### ISSUE TITLE
Unable to open .tar.lzma files made with tar (version 1.3) command

### ISSUE THREAD

**Issue by GM-Script-Writer-62850** [mate-desktop/engrampa#393]
#### Expected behavior

* Able to open file .tar.lzma file made using tar command, eg: `tar caf test.tar.lzma ./`
* Able to open .tar.lzma files made through GUI

#### Actual behavior

* Attempting to open archives ends in error, renaming archive to .tar.xz allows it to open
* Able to open .tar.lzma files made through GUI

#### Steps to reproduce the behavior
[testArchives.zip](https://github.com/mate-desktop/engrampa/files/4781327/testArchives.zip)

1. 
![Screenshot_2020-06-12_15-37-50](https://user-images.githubusercontent.com/564653/84540924-61a51e00-acc4-11ea-9655-d3f69e26bd0b.png)
2. 
![Screenshot_2020-06-12_15-39-03](https://user-images.githubusercontent.com/564653/84540940-6a95ef80-acc4-11ea-9db9-ebac8fb76455.png)

#### MATE general version
```
$ apt-cache policy mate-desktop-common 
mate-desktop-common:
  Installed: 1.24.0-2
  Candidate: 1.24.0-2
  Version table:
 *** 1.24.0-2 500
        500 http://us.archive.ubuntu.com/ubuntu focal/universe amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu focal/universe i386 Packages
        100 /var/lib/dpkg/status

```

#### Package version
```
$ apt-cache policy engrampa
engrampa:
  Installed: 1.24.0-2
  Candidate: 1.24.0-2
  Version table:
 *** 1.24.0-2 500
        500 http://us.archive.ubuntu.com/ubuntu focal/universe amd64 Packages
        100 /var/lib/dpkg/status
```

#### Linux Distribution
Xubuntu 20.04 (Upgraded from 18.04)
XFCE / XFWM4 / Xorg

**Comment by rbuj** [comment]
Make sure the 'lzma' command is available on your system.
Installing lzma support on Fedora:
```
# dnf install -y xz-lzma-compat
```
Installing lzma support on Ubuntu:
```
# dnf install -y lzma
```

**Comment by GM-Script-Writer-62850** [comment]
how was that not already installed...
```
$ apt-cache policy lzma
lzma:
  Installed: 9.22-2.1build1
  Candidate: 9.22-2.1build1
  Version table:
 *** 9.22-2.1build1 500
        500 http://us.archive.ubuntu.com/ubuntu focal/universe amd64 Packages
        100 /var/lib/dpkg/status
```
no changes
i did notice if i download the same lzma via firefox and open it that way it does not give a error but i can't extract it

**Comment by rbuj** [comment]
It seems the tar command failed to get the file list for a .tar.lzma archive on Ubuntu.
```
tar --force-local --no-wildcards -tvf /home/robert/test.tar.lzma --use-compress-program=lzma 
```
Build & Install engrampa with debugging info enabled:
```
$ git submodule init
$ git submodule update
$ ./autogen.sh --prefix=/usr --enable-debug && make && sudo make install
```
Ubuntu 20.04 run log:
```
$ engrampa test.tar.lzma 
[FR] fr-window.c:2849 (action_started):
	LOADING_ARCHIVE [START] (FR::Window)

[FR] fr-window.c:3151 (action_performed):
	LOADING_ARCHIVE [DONE] (FR::Window)

[FR] fr-command.c:589 (fr_command_set_filename):
	filename : /home/robert/test.tar.lzma

[FR] fr-command.c:590 (fr_command_set_filename):
	e_filename : '/home/robert/test.tar.lzma'

[FR] fr-archive.c:697 (action_started):
	LISTING_CONTENT [START] (FR::Archive)

[FR] fr-window.c:2849 (action_started):
	LISTING_CONTENT [START] (FR::Window)

[FR] fr-process.c:685 (start_current_command):
	0/0) 
	LC_MESSAGES=C
	LC_TIME=C
	LC_NUMERIC=C
	tar --force-local --no-wildcards -tvf /home/robert/test.tar.lzma --use-compress-program=lzma 
** ERROR **
tar: Error is not recoverable: exiting now
tar: Child returned status 1
lzma: SetDecoderProperties() error
[FR] fr-archive.c:934 (action_performed):
	LISTING_CONTENT [DONE] (FR::Archive)

[FR] fr-window.c:3151 (action_performed):
	LISTING_CONTENT [DONE] (FR::Window)

```
Fedora run log: (no issue)
```
$ engrampa test.tar.lzma 
[FR] fr-window.c:2849 (action_started):
	LOADING_ARCHIVE [START] (FR::Window)

[FR] fr-window.c:3151 (action_performed):
	LOADING_ARCHIVE [DONE] (FR::Window)

[robert@rawhide engrampa]$ cd
[robert@rawhide ~]$ engrampa test.tar.lzma 
[FR] fr-window.c:2849 (action_started):
	LOADING_ARCHIVE [START] (FR::Window)

[FR] fr-window.c:3151 (action_performed):
	LOADING_ARCHIVE [DONE] (FR::Window)

[FR] fr-command.c:589 (fr_command_set_filename):
	filename : /home/robert/test.tar.lzma

[FR] fr-command.c:590 (fr_command_set_filename):
	e_filename : '/home/robert/test.tar.lzma'

[FR] fr-archive.c:697 (action_started):
	LISTING_CONTENT [START] (FR::Archive)

[FR] fr-window.c:2849 (action_started):
	LISTING_CONTENT [START] (FR::Window)

[FR] fr-process.c:685 (start_current_command):
	0/0) 
	LC_MESSAGES=C
	LC_TIME=C
	LC_NUMERIC=C
	/usr/bin/gtar --force-local --no-wildcards -tvf /home/robert/test.tar.lzma --use-compress-program=lzma 
[FR] fr-archive.c:934 (action_performed):
	LISTING_CONTENT [DONE] (FR::Archive)

[FR] fr-window.c:3151 (action_performed):
	LISTING_CONTENT [DONE] (FR::Window)

```

**Comment by GM-Script-Writer-62850** [comment]
fedora has tar 1.32
ubuntu has tar 1.3

After replacing my tar binary (/bin/tar) with the one from [arch linux](https://archlinux.pkgs.org/rolling/archlinux-core-x86_64/tar-1.32-3-x86_64.pkg.tar.xz.html) the bug can no longer be reproduced using the provided steps
The issue appears to be caused by opening a .tar.lzma created using tar 1.3

1. Use engrampa to open .tar.lzma made with tar 1.32 while tar 1.3 in installed
   + Works
2. Use engrampa to open .tar.lzma made with tar 1.32 while tar 1.32 in installed
   + Works
3. Use engrampa to open .tar.lzma made with tar 1.3 while tar 1.3 in installed
   + Error
4. Use engrampa to open .tar.lzma made with tar 1.3 while tar 1.32 in installed
  + Error

```
$ ls -l /bin/tar*
lrwxrwxrwx 1 root root     13 Jun 14 10:26 /bin/tar -> tar-1.32-arch
-rwxr-xr-x 1 root root 517592 Jun 14 10:02 /bin/tar-1.32-arch
-rwxr-xr-x 1 root root 448112 Mar 14 16:24 /bin/tar-1.3-focal
```

So is this a comparability bug or is tar 1.3 bugged?

**Comment by GM-Script-Writer-62850** [comment]
Did some more testing using older versions of tar and engrampa, this does not appear to be a regression, since no other software i have found gives a error opening the archive i'd say it is a engrampa bug

I attached sample archives in the 1st post here made using several version of tar

**Comment by rbuj** [comment]
Report the bug of tar at https://launchpad.net/ubuntu/+source/tar/+bugs
