### ISSUE TITLE
Translation build problem with Serbian and Lithuanian language

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/engrampa#404]
Translation breaks building, format issue.
```
.............................................................. done.
rm -f lt.gmo && /usr/bin/msgmerge --for-msgfmt -o lt.1po lt.po engrampa.pot && /usr/bin/msgfmt -c --statistics --verbose -o lt.gmo lt.1po && rm -f lt.1po
lt.1po:585: number of format specifications in 'msgid_plural' and 'msgstr[0]' does not match
/usr/bin/msgfmt: found 1 fatal error
lt.1po: 420 translated messages.
make[3]: *** [Makefile:325: lt.gmo] Error 1
````
Same for Serbian translation.
```
................................................................ done.
rm -f sr.gmo && /usr/bin/msgmerge --for-msgfmt -o sr.1po sr.po engrampa.pot && /usr/bin/msgfmt -c --statistics --verbose -o sr.gmo sr.1po && rm -f sr.1po
sr.1po:573: number of format specifications in 'msgid_plural' and 'msgstr[0]' does not match
/usr/bin/msgfmt: found 1 fatal error
sr.1po: 420 translated messages.
make[3]: *** [Makefile:325: sr.gmo] Error 1
```
```
#: src/dlg-update.c:176 src/dlg-update.c:204 src/ui/update.ui:152
#, c-format
msgid ""
"The file has been modified with an external application. If you don't update "
"the file in the archive, all of your changes will be lost."
msgid_plural ""
"%d files have been modified with an external application. If you don't "
"update the files in the archive, all of your changes will be lost."
```
I think we need to add format specification `%d` for singular form in UI file to fix the build issue.
For  the moment i deleted the translations to get 1.24.1 release ready.

**Comment by zhuyaliang** [comment]
@raveit65 How to handle this issue

**Comment by raveit65** [comment]
There are very often translations strings in all repositories after a `tx pull -af` which breaks building.
Most of the time the translator makes a mistake and didn't respect the format, because he didn't compile the package by hand in his local box to check it for errors.
In result the maintainer needs to fix this in an unknown language for him at transifex website.
Well this job eats the spare time of the maintainer dramatically :/
In result i stopped doing this before a release and i fix build issues with a `git restore po/culprit_language.po` :)
Currently there is only one build warning in master which do not break building.
```
  GEN      ja/ja.mo
  GEN    ja/
Warning: Could not merge ja translation for msgid:
Click on this button to save the current selection of advanced add options to a file. The <guilabel>Save Options</guilabel> dialog is displayed. Enter a descriptive filename in the <guilabel>Options Name</guilabel> text box, then click <guibutton>Save</guibutton>.
```
I think we can close the issue as mentioned build issues from 2020 are not exists any more.
