### ISSUE TITLE
Deletion of files with non-latin names from .rar archive fails

### ISSUE THREAD

**Issue by unxed** [mate-desktop/engrampa#411]
#### Expected behaviour

File "тестовый файл 1.тест" should be deleted from this sample archive on pressing \<Del\>\<Enter\> keys in Engrampa.
(.rar is packed to .zip here for github to allow attaching it)
[1234.zip](https://github.com/mate-desktop/engrampa/files/5342363/1234.zip)

#### Actual behaviour

It does not.

#### Steps to reproduce the behaviour

1. Extract 1234.rar from attached 1234.zip
2. Open 1234.rar with Engrampa
3. Try to delete any file or folder from that archive

#### MATE general version
1.24.0

#### Package version
1.24.0-2

#### Linux Distribution
Linux Mint 20 MATE x64

#### Link to downstream report of your Distribution
n/a

**Comment by unxed** [comment]
Dealt with this; in fact, no files are deleted if rar itself is not installed. Maybe we should show some kind of informative error message in such cases?

**Comment by zhuyaliang** [comment]
Please try the latest version
![rar](https://user-images.githubusercontent.com/36913152/227776740-ae1ba8c4-d4f7-4fbd-977f-ed1b171402ec.png)

**Comment by zhuyaliang** [comment]
The problem lies here. You should enable PackageKit installer
```
#ifdef ENABLE_PACKAGEKIT

    {
        char      *secondary_text;
        GtkWidget *dialog;

        secondary_text = g_strdup_printf (_("There is no command installed for %s files.\nDo you want to search for a command to open this file?"),
                          g_content_type_get_description (idata->archive->content_type));
        dialog = _gtk_message_dialog_new (GTK_WINDOW (idata->window),
                          GTK_DIALOG_MODAL,
                          "dialog-error",
                          _("Could not open this file type"),
                          secondary_text,
                          NULL);

        gtk_dialog_add_action_widget (GTK_DIALOG (dialog),
                                      create_button ("process-stop", _("_Cancel")),
                                      GTK_RESPONSE_NO);

        gtk_dialog_add_action_widget (GTK_DIALOG (dialog),
                                      create_button ("edit-find", _("_Search Command")),
                                      GTK_RESPONSE_YES);

        gtk_dialog_set_default_response (GTK_DIALOG (dialog), GTK_RESPONSE_YES);

        g_signal_connect (dialog, "response", G_CALLBACK (confirm_search_dialog_response_cb), idata);
        gtk_widget_show (dialog);

        g_free (secondary_text);
    }

#else /* ! ENABLE_PACKAGEKIT */
```

**Comment by zhuyaliang** [comment]
@unxed Can I close this issue ？

**Comment by unxed** [comment]
Engrampa hangs for me while trying to delete "тестовый файл 1.тест" from 1234.rar on lastest Mint Cinnamon.

**Comment by unxed** [comment]
Not using MATE Desktop currently. Switched to Cinnamon. So can not reproduce.
