### ISSUE TITLE
Compressing file to .gz shows "application-x-generic" icon rather than "package-x-generic" or a gzip icon, and "mate-mime" appears in source

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/engrampa#412]
#### Expected behaviour
compressing file with .gz selected in caja-engrampa "compress" dialog shows gzip icon

#### Actual behaviour
image-missing icon shown, this is true in ALL icon themes tested including mate icon themes

![compress-dialog_11-5-2020](https://user-images.githubusercontent.com/14036792/98204803-a0b36480-1f2e-11eb-8288-b3296c5fe1c2.jpg)

Note that in source file eggfileformatchooser.c we have this block in `get_icon_name (const gchar *mime_type)`

```
  if (mime_type)
    {
      name = g_strconcat ("mate-mime-", mime_type, NULL);

      for(s = name; *s; ++s)
        {
          if (!isalpha (*s) || !isascii (*s))
            *s = '-';
        }
    }

```
neither the mate icon themes nor any others have a mimetype mate-mime-(anything) but gnome-mime-(something) is a common mimetype seen in icon sets. Presumably this was changed by mistake when the package was first forked from file-roller. I tested editing this back to gnome-mine but had the same issue, so presumably this issue comes from somewhere else but we still should not be specifying a "mate-mime-" mimetype anywhere

#### Steps to reproduce the behaviour
right-click on a file, select "compress" then select .gz filetype

#### MATE general version
1.25

#### Package version
engrampa 1.25.0 from git pull 11-3-2020

#### Linux Distribution
Debian Unstable

#### Link to downstream report of your Distribution
None as this is a local build

**Comment by zhuyaliang** [comment]
@lukefromdc Does the problem still exist ?

**Comment by zhuyaliang** [comment]
Perhaps we can set a default icon for tools that do not have a mime file, such as this
```
     mime_type = mime_type_desc[data->supported_types[idx]].mime_type;
     if ((icon_name = g_content_type_get_generic_icon_name (mime_type)) != NULL) {
         gtk_image_set_from_icon_name (GTK_IMAGE (GET_WIDGET ("archive_icon_image")),
                                       icon_name, GTK_ICON_SIZE_DIALOG);
         g_free (icon_name);
     }
     else
     {
         gtk_image_set_from_icon_name (GTK_IMAGE (GET_WIDGET ("archive_icon_image")),
                                       "package-x-generic", GTK_ICON_SIZE_DIALOG);
     }
```

**Comment by zhuyaliang** [comment]
I checked the code again, ```g_content_type_get_generic_icon_name``` does not return ```NULL```, and when the mime does not exist, it returns ```application-x-generic```

**Comment by lukefromdc** [comment]
I just got no change in this behavior when testing https://github.com/mate-desktop/engrampa/pull/473

**Comment by L-U-T-i** [comment]
> I just got no change in this behavior when testing #473

Same here (Rocky Linux 9.1, custom build latest git commit with #473 applied, 'application-x-generic' icon present in 'Adwaita', 'mate' and many other mimetypes directories for  at least 16x16 ÷ 48x48 resolutions).

**Comment by zhuyaliang** [comment]
Please view the ```application-x-generic``` icon. No problem with the code
```eom /usr/share/icons/Adwaita/48x48/mimetypes/application-x-generic.png```

**Comment by lukefromdc** [comment]
In fact, application-x-generic from adwaita icons is exactly what's coming up, 
not package-x-generic. My icon set does NOT inherit from adwaita though,
so I may have a clone of that elsewhere-or it may be coming up regardless
of icon theme

**Comment by lukefromdc** [comment]
That's a different issue, comes up fine for me. Make sure you didn't accidently delete the gzip program that 
provides that format and is called by engrampa

**Comment by zhuyaliang** [comment]
@L-U-T-i I updated the code #473 Please check if problem  has been repaired

**Comment by zhuyaliang** [comment]
@lukefromdc Can I close this issue

**Comment by lukefromdc** [comment]
Yes, it's fixed on my end.
