### ISSUE TITLE
zipping with password deletes file

### ISSUE THREAD

**Issue by tczillay** [mate-desktop/engrampa#432]
#### Expected behaviour
wanted to get a password protected zip from a pdf-file

#### Actual behaviour
zip-file ist very small (208 Bytes), "File" inside shows size of 0
the file which should be compressed ist now size of 0 too!

#### Steps to reproduce the behaviour
don't know how to

#### MATE general version
1.24.0

#### Package version
1.24.0-2

#### Linux Distribution
20.04

**Comment by lukefromdc** [comment]
Does this delete the original file too, or just the copy inside the tarball? The latter is a bug, the former would be a critical (data loss) bug

**Comment by zhuyaliang** [comment]
@tczillay Please check if the latest submitted code issue still exists

**Comment by tczillay** [comment]
cannot reproduce this behavior now. Zipped files won't not kill the original files I tested today

**Comment by zhuyaliang** [comment]
@tczillay Can I close this issue
