### ISSUE TITLE
Can't create zip files when 7-zip 21.02 is installed

### ISSUE THREAD

**Issue by fulalas** [mate-desktop/engrampa#433]
Using Engrampa 1.24.0 and newer fails to create zip files when 7-zip 21.02 is installed -- tested on Slackware x64 current. The following message appears:
![Screenshot_2021-07-10_11-24-43](https://user-images.githubusercontent.com/27843666/125144444-03ba6280-e172-11eb-9eaa-c59808c51754.png)

Can anyone confirm? Is there a way to enable log/debug info?

**Comment by pilarrob** [comment]
You probably replaced 7z file, try to install 21.07, there are two files 7zz and 7zzs and problem is gone, however new version 7zip is not supported by Engrampa (opened issue)

**Comment by qiujiangkun** [comment]
21.07 doesn't help.
I couldn't find 7zzs in 21.07

**Comment by zhuyaliang** [comment]
@qiujiangkun @pilarrob @fulalas I have added support for the latest 7z. If you are interested, you can try it out
[engrampa-472](https://github.com/mate-desktop/engrampa/pull/472)
