### ISSUE TITLE
Who is the arsehole responsible for this abomination?

### ISSUE THREAD

**Issue by AbominableIntelligence** [mate-desktop/engrampa#434]
#### Expected behaviour

Only overwrite selected files when using drag and drop

#### Actual behaviour

All my work is destroyed. All of it. Days of work. Selecting a few files in an archive and dragging and dropping on a thunar window extracts EVERYTHING, not just the selected files.

Please don't ever touch a keyboard again - you shouldn't even be programming your defrost cycle, never mind a computer.

**Comment by mbkma** [comment]
I can not reproduce this behaviour with engrampa and caja. Note that we do not support Thunar officially.
And finally a quick remainder:

>  *  This program is distributed in the hope that it will be useful,
>  *  but WITHOUT ANY WARRANTY; without even the implied warranty of
>  *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
>  *  GNU General Public License for more details.
