### ISSUE TITLE
Feature reguest: wider columns

### ISSUE THREAD

**Issue by chang-zhao** [mate-desktop/engrampa#438]
#### Expected behaviour

Columns "Name" (and especially) "Size" & "Type" should either adjust its width to the content, or restore the width set manually in previous sessions.

#### Actual behaviour

They don't show full info even though there is plenty of space:

<a href='https://postimg.cc/7J3v8Q7m' target='_blank'><img src='https://i.postimg.cc/1XTyFkzh/engrampa01.png' border='0' alt='engrampa01'/></a>

#### Steps to reproduce the behaviour

Open any archive.

#### Package version

The same thing should be corrected in file-roller.

**Comment by zhuyaliang** [comment]
```gsettings set org.mate.engrampa.listing name-column-width 600 (width value)```

**Comment by zhuyaliang** [comment]
@chang-zhao Does this work for you? Can I close this issue?
