### ISSUE TITLE
engrampa uses SI instead of IEC and gives no option to change it.

### ISSUE THREAD

**Issue by 133794m3r** [mate-desktop/engrampa#46]
I don't know why there isn't a _global_ option to set this across _all_ mate-desktop programs. Pluma uses IEC, Atril uses IEC. Now caja has the option to use IEC but it's not a global one amongst the whole suite. I don't see why it'd be such a hard thing to do.

You talked about wanting to be consistent so why is it that this desktop is so schizophrenic, If you want to use SI so be it but there should be options to switch it's size system.

**Comment by Rencer** [comment]
> I dont understand why you need to always use this kind of language.
> 
> This is the commit: [mate-desktop/caja@7fbadf7](https://github.com/mate-desktop/caja/commit/7fbadf79122f06e80dd52937bfec8dea36cc2581)
> Feel free to pull request it, if you need it so much

A simple end-user doesn't even know what are talking about!
What request I have to pull, so Engrampa shows the file size in binary?
