### ISSUE TITLE
New feature request

### ISSUE THREAD

**Issue by fixit7** [mate-desktop/engrampa#463]
#### Expected behaviour
I would like to ask that there be an option when deleting files from an archive without getting prompted to confirm the removal.
Thanks.

**Comment by fixit7** [comment]
I would like to ask that there be an option when deleting files from an archive without getting prompted to confirm the removal.
Thanks.

**Comment by thesquash** [comment]
What happened here?  Was this feature secretly completed?

**Comment by fixit7** [comment]
I do not understand what you re asking?

Sent via personal computer It "It is always too soon to quit."


     On Wednesday, September 14, 2022, 07:58:53 PM CDT, Gordon N. Squash ***@***.***> wrote:  
 
 


What happened here? Was this feature secretly completed?
