### ISSUE TITLE
Cannot encrypt file list with RAR.

### ISSUE THREAD

**Issue by MarioMey** [mate-desktop/engrampa#467]
#### Expected behaviour
I should can encrypt with password the file list.

#### Actual behaviour
Option "Also encrypt file list" ("Cifrar también la lista de archivos" in spanish) is not clickable. Nor RAR, neither any of the other file types/containers.
![imagen](https://user-images.githubusercontent.com/4954109/207138311-549b9bd4-fe21-4fe3-b12f-f861362b5aa6.png)

#### Steps to reproduce the behaviour
- New file
- Choose RAR
- Click on "More options"
- Look at that option

#### RAR versions
```
$ rar -version
RAR 5.50   Copyright (c) 1993-2017 Alexander Roshal   11 Aug 2017
Trial version             Type 'rar -?' for help
```
With...
`rar a -m5 -hp comprimido.rar ./cosas/*`
... I can encrypt perfectly with password.

#### MATE general version
1.24.1

#### Package version
Gestor de archivadores Engrampa 1.24.1

#### Linux Distribution
Debian 11 x64

#### Link to bugreport of your Distribution (requirement)
https://www.debian.org/Bugs/Reporting

**Comment by zhuyaliang** [comment]
Please try using the latest version to see if the problem exists

**Comment by zhuyaliang** [comment]
@MarioMey  Can I close this issue

**Comment by MarioMey** [comment]
Today I compressed some files in a RAR with encription also in file list. So... close it, thanks.
