### ISSUE TITLE
creating archive that doesnt following links

### ISSUE THREAD

**Issue by philipzae** [mate-desktop/engrampa#48]
i extracted an archive file which had directory links to other folders, and when i tried to create an archive file from the same files i extracted, it followed the directory links and pulled in all files and directories underneath it. i would like to request that an option be added to the archive creation dialog under 'other options' of not following symbolic links.

**Comment by monsta** [comment]
Same as https://github.com/mate-desktop/engrampa/issues/13. Gotta fix it someday...
