### ISSUE TITLE
Cannot compress some set of files that included a file with new line

### ISSUE THREAD

**Issue by davidhedlund** [mate-desktop/engrampa#497]
#### Expected behaviour
Succeed compression. tar could compress the files without any errors:

#### Actual behaviour
* An error occured while adding files to the archive

Succeeded to compress files
* ear
* jar

Compress files (not evaluated the content because I could not open these compressed file types even with compression of a simple working text file)
* ar
* arj
* odp
* ods
* odt
* otp
* ots
* ott
* war

Failed to compress files (with error message when engrampa is used: engrampa GUI for test case 1, engrampa GUI for test case 2, engrampa command line for test case 1. No error message for engrampa command line for test case 2)
* tar
* tar.7z
* tar.bz2
* tar.gz
* tar.lzma
* tar.xz
![image](https://github.com/mate-desktop/engrampa/assets/6416073/8a3f50e4-338e-414a-831b-cbc2683db05d)

Failed to compress files (without error message --  (with error message when engrampa is used: engrampa GUI for test case 1, engrampa GUI for test case 1. No error message for engrampa GUI for test case 2, engrampa GUI for test case 2)
* 7z
* cbz
* epub
* exe
* zip

#### Steps to reproduce the behaviour
I was experimenting with file names and discovered by coincidence that I could not compress the files. So I reduced the number of files as much as possible to reproduce the bug, but landed on a very long set of combination that trigger the bug. This is highly unexpected, and I don't know _WHY_ it happens!

##### Test case 1
```
touch a b b~ c d e f 'g'$'\n''.txt' h i j

tar -czvf foo.tar *
engrampa --add-to bar.tar *
```

##### Test case 2
```
# Not dependent of "a". "a" can be replaced with any character
touch 'a'$'\n''.txt'

mkdir -p a
cd a || exit

# The file names "a", "b", and "b~", can not be substituted with other characters
touch a b b~ '#' '{' '|' '}' '~' '$'
cd ..

tar -czvf foo.tar *
engrampa --add-to bar.tar *
```

#### MATE general version
1.26.0

#### Package version
1.26.0-1ubuntu1

#### Linux Distribution
Ubuntu MATE 23.04

#### Link to bugreport of your Distribution (requirement)
https://bugs.launchpad.net/ubuntu/+source/engrampa/+bug/2035669

**Comment by davidhedlund** [comment]
> @davidhedlund Thank you very much for your detailed testing

Good detective work! What should we change the title to?

**Comment by zhuyaliang** [comment]
There is no need to change the title. I think this issue should be caused by the compression tool command using the ``file-list``` parameter
