### ISSUE TITLE
meson.build files are not in released 1.28 tarball generated with distcheck

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/engrampa#511]
#### Expected behaviour
Working releasing with travis-ci

#### Actual behaviour
Meson.build files are missing

#### Steps to reproduce the behaviour

Check released tarball https://github.com/mate-desktop/engrampa/releases/tag/v1.28.0
#### MATE general version

1.28
#### Package version
1.28.0

**Comment by raveit65** [comment]
@mate-desktop/core-team

**Comment by zhuyaliang** [comment]
@raveit65 Can the issue be closed?

**Comment by lukefromdc** [comment]
We now have 1.28.1 with the meson files included 
https://github.com/mate-desktop/engrampa/releases/tag/v1.28.1
so we can close this
