### ISSUE TITLE
Split file

### ISSUE THREAD

**Issue by Mejioy** [mate-desktop/engrampa#514]
#### Expected behaviour
Clicks to resize should change split file size when creating a .7z archive format

#### Actual behaviour
Clicks to resize split file doesn't change size. 

#### Steps to reproduce the behaviour
User select file/files and try to Compress them with utility displayed in File Browser Caja, in case if he choice .7z and press other options;  checked the box "Split into volumes of " and start click on buttons in widget that will no give a result.
![img1](https://github.com/mate-desktop/engrampa/assets/134724414/99cd43bc-f942-42ab-9ba1-be1007817381) 
I noticed one thing: in case when hold LMB on this buttons, that will give you desired result, that will change split file size.
![img2](https://github.com/mate-desktop/engrampa/assets/134724414/2bf23b75-8fd6-49ab-8b58-62177110ccdf)
In case when u create new archive directly from Engrampa Archive Manager, select .7z and press other options widget of split file size will react correctly: it will change split file size after default click
![img3](https://github.com/mate-desktop/engrampa/assets/134724414/b45d12e9-af63-4aab-9812-6eae6b042d2e)
#### MATE general version
1.26.0
caja-1.26.0

#### Package version
1.26.0

**Comment by Mejioy** [comment]
I tried this on the latest version (1.28.1), it works the same

**Comment by zhuyaliang** [comment]
I use archLinux and can properly split archive files in 7z format
I manually build ```engrampa``` from the ```master``` branch

**Comment by lukefromdc** [comment]
I just tested this and it works. Since this was basically ready to go, I created a PR for it, making one change in your patch by increasing maximum filesize from 1000 to 10000MB to accomodate the case of compressing very large files such as multiple root partition images. 

https://github.com/mate-desktop/engrampa/pull/521
