### ISSUE TITLE
Problem unpacking archives with password

### ISSUE THREAD

**Issue by Mejioy** [mate-desktop/engrampa#522]
#### Expected behaviour
Unpacking of archives without any problems

#### Actual behaviour
Errors:
GLib-GIO-CRITICAL **: 09:49:40.743: g_file_new_for_path: assertion 'path != NULL' failed

GLib-GIO-CRITICAL **: 09:49:40.744: g_file_query_filesystem_info: assertion 'G_IS_FILE (file)' failed
Segmentation fault (core dumped)

#### Steps to reproduce the behaviour
Create a .7z or .zip archive with a password
![image](https://github.com/user-attachments/assets/6a186d41-5dae-472e-b9ff-88fdf10bca36)

Fill archive with some file and rerun engrampa.

Use this option:
![image](https://github.com/user-attachments/assets/f856c7e4-2ef5-43b2-b753-b618ba8ba2fe)

Enter the password:
![image](https://github.com/user-attachments/assets/ad16c08c-e073-4f97-8036-36c8575e9e86)

After this engrampa will crash with the following error:
![image](https://github.com/user-attachments/assets/c4e06c44-c7d1-4b63-8d84-bad26ee20e87)

###Note
If you choose a .7z archive and select this option:
![image](https://github.com/user-attachments/assets/2a97e452-e984-47c8-af39-0c934754b297)

Unselecting this option will result in an error, that was mentioned above.

After creating the archive and filling it up, rerun engrampa and open this one archive. First, engrampa will request a password to open the archive. Extracting files from this type of archive does not result in an error.

#### MATE general version
1.28.0

#### Package version
1.28.1

**Comment by Mejioy** [comment]
Tried with an epub type archive, leads to the same problem. It seems the problem does not depend on the archive type.

**Comment by Mejioy** [comment]
The extraction of any archives using Caja-Engrampa does not result in an error. 
![image](https://github.com/user-attachments/assets/db96bd57-48de-4555-979d-574fd1c2ba9c)

**Comment by lukefromdc** [comment]
This looks like another one of those problems exposed by the glib 2.78 and later changes.

**Comment by Mejioy** [comment]
I believe this is not the case, as the issue was observed with the glib version 2.65.3. Following your comment, I have tested the issue in the distribution using the glib 2.80 version, and the behavior remains unchanged.

**Comment by lukefromdc** [comment]
That might mean we need a different fix.Looking more closely it looks like a filepath is not being found. We have g_file_new_for_path not getting the path needed passed to it, thus it comes up NULL and engrampa crashes

**Comment by Mejioy** [comment]
I have fixed the issue myself using a patch - https://github.com/mate-desktop/engrampa/commit/450f2ce034f9ded032f06a80c00f5c762918a7dd. Would you please verify the work and let me know if there are any issues? Alternatively, please let me know where I might have made a mistake.

**Comment by lukefromdc** [comment]
Fixed by
https://github.com/mate-desktop/engrampa/pull/519
https://github.com/mate-desktop/engrampa/commit/4e0906a4dd0dfd0703ac688551bdcac5ff00a368
