### ISSUE TITLE
rar support via unar doesn't work

### ISSUE THREAD

**Issue by ghost** [mate-desktop/engrampa#59]
"Could not open this file type
There is no command installed for RAR archive files.
Do you want to search for a command to open this file?"

engrampa 1.8.0
unar 1.8.1
Fedora 20

Example rar file:
http://www.philipp-winterberg.com/download/example.rar

**Comment by JonasCz** [comment]
In Ubuntu MATE, it seems like unrar is not installed by default, thus engrampa cannot open rar files. Don't know if it's possible, but maybe make unrar a dependency ?

**Comment by sc0w** [comment]
engrampa works fine with unar and unrar, you have this two options

I recommend unar because it is free software

If you like to be a dependency, you can talk with the maintainer of your linux distribution

**Comment by sc0w** [comment]
anyway, If we have two options, it doesn't need dependency, the user can decide
