### ISSUE TITLE
Cyrillics isn't correctly displayed in zip files

### ISSUE THREAD

**Issue by sergeyfromminsk** [mate-desktop/engrampa#71]
Names of files on Cyrillics aren't correctly displayed in zip archives. In ubuntu without mate (14.04, 14.10) file-roller displays them correctly. For example this zip-archive - http://1drv.ms/11Sq7Om . Ubuntu - mate 14.10.
Here picture of this bug -﻿ http://1drv.ms/11Ssd0z

**Comment by monsta** [comment]
I confirm it happens with the mentioned archive. Running Debian Testing with engrampa built from git master (1.9.x).

**Comment by sc0w** [comment]
@sergeyfromminsk the links http://1drv.ms/11Sq7Om and﻿ http://1drv.ms/11Ssd0z don't work

can someone give us a file with cyrillics ?

**Comment by monsta** [comment]
Looks like we need an archive created in Windows... because when I create the archive with Engrampa, Cyrillic symbols are displayed correctly there.

**Comment by sc0w** [comment]
@sergeyfromminsk I close this issue for now, but feel free to reopen it if you give us a zip file with this bug
