### ISSUE TITLE
[RPMLint]   engrampa voidreturn fr-window.c:6747, 6757

### ISSUE THREAD

**Issue by posophe** [mate-desktop/engrampa#74]
A function uses a 'return;' statement, but has actually a value
to return, like an integer ('return 42;') or similar.

voidreturn fr-window.c:6747, 6757

**Comment by monsta** [comment]
which function is it?

**Comment by monsta** [comment]
Seems to be fixed in https://github.com/mate-desktop/engrampa/commit/28c596789cf64a2df0005362b1595a73f0ab2567.
