### ISSUE TITLE
Caja extension has incomplete about dialog

### ISSUE THREAD

**Issue by monsta** [mate-desktop/engrampa#77]
i.e. no version, no copyright, no author...

**Comment by mf0hka** [comment]
Looks like its working to me.
(Mate 1.8)


![screenshot from 2015-02-01 15 50 04](https://cloud.githubusercontent.com/assets/6516504/5993809/3f998e2e-aa2a-11e4-9cf3-c3d3bc258b7f.png)

**Comment by monsta** [comment]
@mf0hka: caja extension, not engrampa itself.
anyway, @stefano-k fixed it... almost :) the copyright years are somewhat outdated, and no MATE developers mentioned.
