### ISSUE TITLE
Symlinks can causes unextractable archives.

### ISSUE THREAD

**Issue by maandree** [mate-desktop/engrampa#80]
If you create an archive that contains a symlink,
this archive will not be extractable by engrampa
if the symlink is a link to itself, its parent directory
or any ancestor.

Engrampa should not follow symlinks whose
real path is itself an ancestor's real path.
**Additional** engrampa should *not* exclude
broken symlinks.

Note that engrampa is able to create archives
containing symlinks like this, but it is not able
to extract them.

**Comment by sc0w** [comment]
commit in file-roller

**added option to follow symbolic links**

https://git.gnome.org/browse/file-roller/commit/?id=d23d89e66a4582254a1230382bb95d1c7167c0bf

**Comment by monsta** [comment]
Same as https://github.com/mate-desktop/engrampa/issues/13. We'll add that fix from file-roller later.
