### ISSUE TITLE
not able to open packages with name tar-1.bz2

### ISSUE THREAD

**Issue by jmssil** [mate-desktop/engrampa#94]
I downloaded thunderbird twice, opening with engrampa. The second time, engrampa was not able to open the package, since its name was thunderbird-38.1.0.tar-1.bz2 (note the -1).

**Comment by flexiondotorg** [comment]
Engrampa won't recognise that file extension as a mime-type it can handle. Please rename the file and then extract, this is not something we can fix.

**Comment by infirit** [comment]
Which version of engrampa are you using? I remember applying a patch for bug very similar to this which ended up in engrampa 1.10.

**Comment by jmssil** [comment]
I'm using 1.10.0.

Engrampa could use a utility like "file" to get the file type.

Moreover, if I first bunzip2 the file, getting thunderbird-38.1.0.tar-1, Engrampa is able to open the thunderbird-38.1.0.tar-1 file correctly.

Can this issue be reopened? I think it is very common to download the same file more than once with Firefox. After the first time you won't be able to use Engrampa to handle the download, you will have to access the /tmp directory and remove the older files, but that eliminates the easiness of using of Engrampa.

**Comment by infirit** [comment]
For me it works as follows.

It opens the file but shows not the contents of the tar but the tar. Then when I double click on the tar file it opens another engrampa window which has the contents of the tar. Do you see the same?

**Comment by jmssil** [comment]
Yes, I confirm that behaviour.

**Comment by infirit** [comment]
The problem is that Gio reports the file as a plain bzip2 not bzip2 compressed tar. Engrampa (and file-roller) then treat it as such and just show the contents of what is compressed. We can not go and second guess what Gio is telling us..

**Comment by jmssil** [comment]
Maybe I should report it to Gio then? What is that Gio, is it this: https://en.wikipedia.org/wiki/GIO_%28software%29?
